
CREATE TABLE "table_metrics_scan_report" (
    metric_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(255) NOT NULL,   -- fk
    snapshot_id BIGINT NOT NULL,
    filter JSONB NOT NULL,
    schema_id INT NOT NULL,
    projected_field_ids INTEGER[] NOT NULL,
    projected_field_names TEXT[] NOT NULL,
    metrics JSONB NOT NULL,
    metadata JSONB
);

CREATE TABLE "table_metrics_commit_report" (
    metric_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(255) NOT NULL,   -- fk
    snapshot_id BIGINT NOT NULL,
    sequence_number BIGINT NOT NULL,
    operation VARCHAR(255) NOT NULL,
    metrics JSONB NOT NULL,
    metadata JSONB
);
