
CREATE TABLE "table_metrics_commit_report" (
    metric_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(255) NOT NULL,   -- fk
    snapshot_id BIGINT NOT NULL,
    filter TEXT NOT NULL,
    schema_id INT NOT NULL,
    projected_field_ids TEXT NOT NULL,  -- delimited list of field ids
    projected_field_names TEXT NOT NULL,  -- delimited list of field names
    metrics TEXT NOT NULL,
    metadata TEXT
)

--     pub struct ScanReport {
--     #[serde(rename = "table-name")]
--     pub table_name: String,
--     #[serde(rename = "snapshot-id")]
--     pub snapshot_id: i64,
--     #[serde(rename = "filter")]
--     pub filter: Box<Expression>,
--     #[serde(rename = "schema-id")]
--     pub schema_id: i32,
--     #[serde(rename = "projected-field-ids")]
--     pub projected_field_ids: Vec<i32>,
--     #[serde(rename = "projected-field-names")]
--     pub projected_field_names: Vec<String>,
--     #[serde(rename = "metrics")]
--     pub metrics: std::collections::HashMap<String, MetricResult>,
--     #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
--     pub metadata: Option<std::collections::HashMap<String, String>>,
--     }