//! Checks audit records emitted by a realistic request sequence against the format
//! contract.
//!
//! The committed fixtures in `lakekeeper` pin the shape of the scenarios they cover, but a
//! fixture is generated by the test that asserts against it — so a wrongly built event
//! produces a fixture that agrees with it, and neither notices. This test instead states
//! rules that hold for *any* audit record and checks them against records produced by
//! going through the real service layer, which reaches paths no fixture exercises.
//!
//! It registers the audit listener on its own `ApiContext` only. The shared test harness
//! deliberately does not register it, so no other test is affected by this file.
//!
//! # This file is meant to grow
//!
//! The rules below apply to any record, but they only ever see records something actually
//! emitted — so coverage is exactly the set of request sequences exercised here, and that
//! set starts small. At the time of writing it is two records: one `create_namespace` that
//! succeeds and one lookup of an absent namespace that is denied. Everything else the audit
//! log can emit is unchecked by this file.
//!
//! Reached today: `create_namespace`, `create_table`, `get_metadata`, `list_tables`,
//! `update_properties` and `drop`, across both an `allowed` and a `denied` decision — seven
//! records, which between them carry eight keys no committed fixture emits (`name`,
//! `properties`, `purge`, `table_id`, `removed-properties`, `updated-properties`, and the
//! `ResourceNotFound` failure reason).
//!
//! Not yet reached, in rough order of how cheap each is to add:
//!
//! - views, and table commits, which carry `target-refs` and `update-kinds`
//! - the plural `actions` / `entities` form: every call here checks one action against one
//!   entity, so that whole branch of the record shape is unexercised
//! - per-decision entries carrying `id`, `for-principal` or `determined_by`, which need a
//!   batch-style check rather than a single one
//! - the operational family (`operation` / `outcome` / `context`), which grant changes emit
//! - a real authorizer instead of `AllowAllAuthorizer`. `ActionForbidden` and
//!   `CannotSeeResource` are unreachable here — only `ResourceNotFound` is — and
//!   `random_request_metadata()` is unauthenticated, so real actors and user agents are too.
//!   The OpenFGA authorizer is the cheap way in: CI already provisions it.
//!
//! Adding a case is cheap: drive another call through `CatalogServer` or `ApiServer` before
//! the sleep, and the existing rules apply to whatever it emits. A good case is one that
//! reaches a code path no other case here reaches — a new assertion is worth less than a
//! new record shape, because the rules are already general and it is the inputs that are
//! narrow.
//!
//! If you are here because you changed the audit log format, see the audit log section of
//! `docs/docs/developer-guide.md`: extending this file is part of that change.

use std::sync::Arc;

use iceberg::NamespaceIdent;
use lakekeeper::{
    api::iceberg::v1::{
        DataAccess, NamespaceParameters, namespace::NamespaceService as _,
        tables::TablesService as _,
    },
    server::CatalogServer,
    service::{
        authz::AllowAllAuthorizer,
        events::backends::audit::{AuditEventListener, contract},
    },
};
use lakekeeper_integration_tests::{
    SetupTestCatalog, create_table_request, memory_io_profile, random_request_metadata,
};
use sqlx::PgPool;

#[derive(Clone, Default)]
struct CapturedLogs(Arc<std::sync::Mutex<Vec<u8>>>);

impl std::io::Write for CapturedLogs {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0.lock().expect("log buffer poisoned").extend(buf);
        Ok(buf.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

impl tracing_subscriber::fmt::MakeWriter<'_> for CapturedLogs {
    type Writer = Self;
    fn make_writer(&self) -> Self::Writer {
        self.clone()
    }
}

/// Every audit record captured so far, envelope keys stripped.
fn audit_records(logs: &CapturedLogs) -> Vec<serde_json::Value> {
    let bytes = logs.0.lock().expect("log buffer poisoned").clone();
    String::from_utf8(bytes)
        .expect("log output is utf-8")
        .lines()
        .filter_map(|line| serde_json::from_str::<serde_json::Value>(line).ok())
        .filter(|record| record.get("event_source").and_then(|v| v.as_str()) == Some("audit"))
        .map(contract::contract_fields)
        .collect()
}

#[sqlx::test]
async fn audit_records_from_a_real_request_sequence_satisfy_the_contract(pool: PgPool) {
    let logs = CapturedLogs::default();
    // Thread-local, not global: `sqlx::test` runs on a current-thread runtime, so the
    // detached `tokio::spawn` that dispatches audit events is polled on this same thread
    // and sees this subscriber. A global subscriber would race with other test binaries.
    // Mirrors the binary's formatter so the captured records are shaped like production's.
    let _guard = tracing::subscriber::set_default(
        tracing_subscriber::fmt()
            .json()
            .flatten_event(true)
            .with_current_span(false)
            .with_span_list(true)
            .with_writer(logs.clone())
            .finish(),
    );

    let (ctx, warehouse_response) = SetupTestCatalog::builder()
        .pool(pool.clone())
        .storage_profile(memory_io_profile())
        .authorizer(AllowAllAuthorizer::default())
        .number_of_warehouses(1)
        .build()
        .setup()
        .await;

    // Only this context emits audit events; the shared harness is untouched.
    ctx.v1_state
        .events
        .append(Arc::new(AuditEventListener))
        .await;

    let warehouse = warehouse_response.warehouse_id.to_string();
    let namespace = NamespaceIdent::from_vec(vec!["audit_corpus".to_string()]).unwrap();

    // A create that succeeds, then a lookup of something absent so a genuine denial or
    // not-found path is exercised too.
    let _ = CatalogServer::create_namespace(
        Some(warehouse.clone().into()),
        iceberg_ext::catalog::rest::CreateNamespaceRequest {
            namespace: namespace.clone(),
            properties: Some(std::collections::HashMap::from([(
                "owner".to_string(),
                "audit-corpus".to_string(),
            )])),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    let namespace_params = NamespaceParameters {
        prefix: Some(warehouse.clone().into()),
        namespace: namespace.clone(),
    };

    // A table, which reaches the `create_table` action and its `name` / `table_id` context.
    let created = CatalogServer::create_table(
        namespace_params.clone(),
        create_table_request(Some("audited_table".to_string()), None),
        DataAccess::not_specified(),
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Loading it reaches `get_metadata` on an entity that carries a table id and location,
    // rather than only a namespace.
    let _ = CatalogServer::load_table(
        lakekeeper::api::iceberg::v1::TableParameters {
            prefix: Some(warehouse.clone().into()),
            table: iceberg::TableIdent::new(namespace.clone(), "audited_table".to_string()),
        },
        lakekeeper::api::iceberg::v1::tables::LoadTableRequest::builder().build(),
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Listing reaches an action whose entity is the namespace but whose result is a set,
    // and it is one of the few calls that can emit the plural `entities` form.
    let _ = CatalogServer::list_tables(
        namespace_params.clone(),
        lakekeeper::api::iceberg::v1::ListTablesQuery {
            page_token: lakekeeper::api::iceberg::v1::PageToken::NotSpecified,
            page_size: None,
            return_uuids: true,
            return_protection_status: false,
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // Property updates carry `updated-properties` and `removed-properties`, the two
    // hyphenated action context keys.
    let _ = CatalogServer::update_namespace_properties(
        namespace_params.clone(),
        iceberg_ext::catalog::rest::UpdateNamespacePropertiesRequest {
            removals: Some(vec!["owner".to_string()]),
            updates: Some(std::collections::HashMap::from([(
                "retention".to_string(),
                "30d".to_string(),
            )])),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // A drop with purge, which carries the `purge` context key.
    if created.is_ok() {
        let _ = CatalogServer::drop_table(
            lakekeeper::api::iceberg::v1::TableParameters {
                prefix: Some(warehouse.clone().into()),
                table: iceberg::TableIdent::new(namespace.clone(), "audited_table".to_string()),
            },
            lakekeeper::api::iceberg::v1::DropParams {
                purge_requested: true,
                force: false,
            },
            ctx.clone(),
            random_request_metadata(),
        )
        .await;
    }

    // Finally a lookup of something absent, so a genuine denial is in the corpus too.
    let _ = CatalogServer::namespace_exists(
        NamespaceParameters {
            prefix: Some(warehouse.clone().into()),
            namespace: NamespaceIdent::from_vec(vec!["does_not_exist".to_string()]).unwrap(),
        },
        ctx.clone(),
        random_request_metadata(),
    )
    .await;

    // The dispatch is fire-and-forget, so give the runtime a chance to poll those tasks.
    tokio::time::sleep(std::time::Duration::from_millis(500)).await;

    let records = audit_records(&logs);
    assert!(
        !records.is_empty(),
        "captured no audit records at all. Either the listener is not registered on this \
         context, or the detached dispatch task was never polled — an empty corpus must not \
         read as a pass."
    );

    for (index, record) in records.iter().enumerate() {
        contract::assert_satisfies(record, &format!("record {index}"));
    }

    eprintln!("audit corpus: {} record(s) checked", records.len());
}
