[build]
pre-build = ["""
    apt-get update -qq && apt-get install -yqq curl --no-install-recommends && \
    curl -sL https://deb.nodesource.com/setup_23.x | bash - && \
    apt-get install -y nodejs  && \
    node -v && npm -v
    """]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main@sha256:08ee3c5659d0c39f1fe4de4206ee3597260804f4411630416b5db38412d8eb2b"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:cf091033b6c4b0416a03d181080ad45c418248a262867a623306748a2c02a3c2"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main@sha256:6a878141c73929d380b19b51eefb85b7ad5ff931d63888a0efef242aa368da66"
