/*
 * Apache Iceberg REST Catalog API
 *
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::catalog::rest::metrics::expression::Expression;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AndOrExpression {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "left")]
    pub left: Box<Expression>,
    #[serde(rename = "right")]
    pub right: Box<Expression>,
}

impl AndOrExpression {
    pub fn new(r#type: String, left: Expression, right: Expression) -> AndOrExpression {
        AndOrExpression {
            r#type,
            left: Box::new(left),
            right: Box::new(right),
        }
    }
}
