[package]
name = "lakekeeper-bin"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
description = """
This is Lakekeeper, a catalog for Iceberg tables.
"""

[[bin]]
name = "lakekeeper"
path = "src/main.rs"

[features]
default = []
all = ["ui"]
ui = ["dep:lakekeeper-console"]

[dependencies]
anyhow = { workspace = true }
clap = { version = "^4.5", features = ["derive"] }
figment = { workspace = true }
lakekeeper = { path = "../lakekeeper", features = ["all"] }
lakekeeper-authz-openfga = { path = "../authz-openfga" }
lakekeeper-console = { git = "https://github.com/lakekeeper/console", rev = "7958d9f", optional = true }
limes = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
figment = { workspace = true, features = ["test"] }
