//! One JSON Schema per emitter, generated from the registry of the running binary.
//!
//! The schema is the ground truth of an emitter's audit format: every registered part, context
//! and vocabulary enum appears under `$defs`, with the doc comments as descriptions. It is
//! generated by a test in a crate that links every contributing crate, committed at
//! `audit-format/schema.json`, validated against by the tests, diffed across the merge base by
//! the format checker, and published to the documentation site.
//!
//! A crate cannot see another crate's registrations unless the linker keeps that crate's
//! objects, which it does only when something references them. So the schema is assembled in
//! two steps that need no linker cooperation: every crate that declares audit types commits a
//! **crate schema**, the definitions of its own types, written by its own unit tests
//! ([`crate_schema`]); and one test in a crate that sees every crate schema file merges them
//! per emitter into the committed schema ([`merge_crate_schemas`]).
//!
//! Two properties make the extra step worth it, and both are lost by generating the schema in
//! one place. A crate's schema is written by that crate's own test binary, where its
//! registrations are certainly linked, so a definition cannot go missing without a test
//! failing; and the file sits in the crate, so a pull request touching one crate shows that
//! crate's schema diff next to the change that caused it.
//!
//! Available under `test-utils`, so the tests of other emitting crates generate their crate
//! schema with this implementation. Debug builds only, like the registry it reads: see
//! [`Registration::require_registry`].

use std::collections::{BTreeMap, BTreeSet};

use schemars::{SchemaGenerator, generate::SchemaSettings};
use serde_json::{Map, Value, json};

use super::part::{Kind, Registration};

/// The JSON Schema dialect every audit schema declares.
pub const SCHEMA_DIALECT: &str = "https://json-schema.org/draft/2020-12/schema";

/// The registrations that describe a format, filtered by `keep`.
///
/// The probe types declared inside `#[cfg(test)] mod tests` are left out: they exist to
/// exercise the attribute and reach no record, so a schema that listed them would promise
/// shapes no consumer ever meets. They are recognised by `::tests::` in the type path, which
/// is where a type declared in such a module always sits.
fn registrations(keep: impl Fn(&Registration) -> bool) -> Vec<&'static Registration> {
    let mut regs: Vec<&Registration> = Registration::all()
        .filter(|r| !(r.type_name)().contains("::tests::"))
        .filter(|r| keep(r))
        .collect();
    regs.sort_by_key(|r| (r.type_name)());
    regs
}

/// Strip `null` from every optional property, in place and at every depth.
///
/// A field with no value is left out of the record; nothing emits `null`. The schema
/// generator does not know that — it renders `Option<T>` as "T or null" — so without this
/// the schema would promise a shape the emitter cannot produce, and a consumer would write a
/// parser for a value they will never see. A property that is required keeps whatever it
/// has: `null` there would be a real value, not an absence.
fn drop_null_from_optionals(schema: &mut Value) {
    if let Some(object) = schema.as_object_mut() {
        let required: Vec<&str> = object
            .get("required")
            .and_then(Value::as_array)
            .map(|r| r.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let optional: Vec<String> = object
            .get("properties")
            .and_then(Value::as_object)
            .map(|p| {
                p.keys()
                    .filter(|name| !required.contains(&name.as_str()))
                    .cloned()
                    .collect()
            })
            .unwrap_or_default();
        if let Some(properties) = object.get_mut("properties").and_then(Value::as_object_mut) {
            for name in optional {
                if let Some(spec) = properties.get_mut(&name) {
                    drop_null_alternative(spec);
                }
            }
        }
        for value in object.values_mut() {
            drop_null_from_optionals(value);
        }
    } else if let Some(array) = schema.as_array_mut() {
        for value in array {
            drop_null_from_optionals(value);
        }
    }
}

/// Remove the `null` alternative from one property, in whichever of the two forms the
/// generator wrote it: a type list for a scalar, an `anyOf` branch for a type that has a
/// definition of its own.
fn drop_null_alternative(spec: &mut Value) {
    let Some(object) = spec.as_object_mut() else {
        return;
    };
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        let kept: Vec<Value> = kinds.iter().filter(|k| *k != "null").cloned().collect();
        if kept.len() != kinds.len() {
            let kept = if let [only] = kept.as_slice() {
                only.clone()
            } else {
                Value::Array(kept)
            };
            object.insert("type".into(), kept);
        }
    }
    let Some(branches) = object.get("anyOf").and_then(Value::as_array) else {
        return;
    };
    let kept: Vec<Value> = branches
        .iter()
        .filter(|branch| branch["type"] != "null")
        .cloned()
        .collect();
    // Unchanged, or nothing but `null` — which would leave the property with no schema at
    // all, so it stays as the generator wrote it.
    if kept.len() == branches.len() || kept.is_empty() {
        return;
    }
    // One alternative left, and it is an object, so it is the property's schema and takes the
    // place of the branch list. Keys the property already carries win: `description` there is
    // the field's own doc comment, not the referenced type's. Anything else keeps its branch
    // list, because removing it would leave the property with no schema at all.
    match kept.as_slice() {
        [only] if only.is_object() => {
            object.remove("anyOf");
            for (key, value) in only.as_object().expect("checked by the guard") {
                object.entry(key.clone()).or_insert_with(|| value.clone());
            }
        }
        _ => {
            object.insert("anyOf".into(), Value::Array(kept));
        }
    }
}

/// Each key as a property of the object it belongs to, keyed by the object and the key: the
/// schema schemars writes for the type the key holds, from the generator the rest of the
/// document is written with, so a part a key holds lands under `$defs` like any other. An
/// `entity` key holds nothing, and its value is a string. The key's doc comment is the
/// property's description.
///
/// The keys of `regs`, and every key of an `action` or an `entity` whoever registered it: an
/// action of one crate carries the keys Lakekeeper declares for that object.
type KeySchemas = BTreeMap<(&'static str, &'static str), Value>;

fn key_schemas(generator: &mut SchemaGenerator, regs: &[&Registration]) -> KeySchemas {
    let mut out = KeySchemas::new();
    let shared = registrations(
        |reg| matches!(reg.kind, Kind::Keys { object, .. } if matches!(object, "action" | "entity")),
    );
    for reg in regs.iter().copied().chain(shared) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        for name in names {
            out.entry((object, name.text)).or_insert_with(|| {
                let mut spec = name.value.map_or_else(
                    || json!({ "type": "string" }),
                    |schema| schema(generator).to_value(),
                );
                if let Some(object) = spec.as_object_mut() {
                    object.insert("description".into(), json!(name.doc));
                }
                spec
            });
        }
    }
    out
}

/// The definitions the registrations contribute, plus every type they reference.
///
/// # Panics
///
/// If two registered types want the same `$defs` name. A definition is keyed by the type's
/// short name, so two types of one emitter called `Context` in different modules would
/// otherwise silently become one, and whichever lost would vanish from the schema while its
/// records kept being emitted.
fn definitions(regs: &[&Registration]) -> BTreeMap<String, Value> {
    let mut generator = SchemaGenerator::new(SchemaSettings::draft2020_12());
    let key_schemas = key_schemas(&mut generator, regs);
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    let mut claimed: BTreeMap<String, &'static str> = BTreeMap::new();
    let mut claim = |name: &str, type_name: &'static str| {
        if let Some(other) = claimed.insert(name.to_owned(), type_name) {
            assert_eq!(
                other, type_name,
                "`{name}` is the schema name of two registered types, {other} and \
                 {type_name}. One would replace the other in the schema. Rename one of them."
            );
        }
    };
    for reg in regs {
        match reg.kind {
            Kind::Part | Kind::Context | Kind::Shape { .. } => {
                let (Some(schema), Some(name)) = (reg.schema, reg.schema_name) else {
                    continue;
                };
                let mut schema = schema(&mut generator).to_value();
                if let Some(object) = schema.as_object_mut() {
                    object.insert("x-audit-kind".into(), json!(reg.kind.as_str()));
                    if let Kind::Shape { record_type } = reg.kind {
                        pin_record_type(object, record_type);
                    }
                }
                let name = name().to_string();
                claim(&name, (reg.type_name)());
                defs.insert(name, schema);
            }
            // A key is published as a property of the object it belongs to, with its own
            // description, so a key set needs no definition of its own.
            Kind::Keys { .. } => {}
            Kind::Values { .. } => {
                // A name is a string in a list, so JSON Schema gives it nowhere to carry its
                // own description. This map is where a variant's doc comment reaches a
                // consumer; without it the schema lists the names and explains none of them.
                let descriptions: BTreeMap<&str, &str> = reg
                    .kind
                    .names()
                    .iter()
                    .filter(|name| !name.doc.is_empty())
                    .map(|name| (name.text, name.doc))
                    .collect();
                let mut names: Vec<&str> = reg.kind.names().iter().map(|n| n.text).collect();
                names.sort_unstable();
                // An open value set lists its values beside `type`, not as an `enum`, so a
                // validator accepts a value a later release adds. A closed set cannot grow
                // without a format change, so `enum` states exactly what it is.
                let listed = match reg.kind {
                    Kind::Values { closed: false, .. } => "x-audit-values",
                    _ => "enum",
                };
                let mut def = json!({
                    "type": "string",
                    listed: names,
                    "x-audit-kind": reg.kind.as_str(),
                    "x-audit-field": reg.kind.wire_place(),
                });
                // What a vocabulary says about its own values, keyed by value.
                if !descriptions.is_empty()
                    && let Some(object) = def.as_object_mut()
                {
                    object.insert("x-audit-descriptions".into(), json!(descriptions));
                }
                let name = short_type_name((reg.type_name)());
                claim(&name, (reg.type_name)());
                defs.insert(name, def);
            }
        }
    }
    // Types the parts reference but that are not registered themselves, if any, and every
    // registered type the generator chose to reference rather than inline. An unregistered
    // one still reaches a consumer, so it is kinded here too: the kind is how a reader of the
    // schema tells a value set from an object, and a definition without one says neither.
    for (name, schema) in generator.take_definitions(true) {
        let mut schema = schema;
        if let Some(object) = schema.as_object_mut() {
            let values = object.contains_key("enum")
                || object
                    .get("oneOf")
                    .and_then(Value::as_array)
                    .is_some_and(|variants| variants.iter().all(|v| v.get("const").is_some()));
            object
                .entry("x-audit-kind")
                .or_insert_with(|| json!(if values { "enum" } else { "part" }));
        }
        defs.entry(name).or_insert(schema);
    }
    for schema in defs.values_mut() {
        drop_null_from_optionals(schema);
    }
    add_audit_record(&mut defs, regs);
    link_carried_keys(&mut defs, regs, &key_schemas);
    type_nested_keys(&mut defs, regs, &key_schemas);
    defs
}

/// The objects whose keys sit beside the value that names them, rather than nested under it.
///
/// Each entry is the field carrying that value, the object it sits in, and the type its keys
/// hold when they declare none: an entity field's value is a `String` in the type that
/// carries it, while an action's is a three-way choice each key has to declare.
/// The flattened pairs: the wire field naming the thing, the schema definition it sits in,
/// the `keys_of` vocabulary holding that object's keys, and the type a key takes when it
/// declares none.
const FLATTENED: [(&str, &str, &str, Option<&str>); 2] = [
    ("action_name", "ActionRecord", "action", None),
    ("entity_type", "EntityRecord", "entity", Some("string")),
];

/// Every key a vocabulary declares for `object`.
fn keys_of_object(regs: Vec<&'static Registration>, object: &str) -> BTreeSet<&'static str> {
    regs.into_iter()
        .filter_map(|reg| match reg.kind {
            Kind::Keys { object: o, names } if o == object => Some(names),
            _ => None,
        })
        .flatten()
        .map(|name| name.text)
        .collect()
}

/// Every key a variant says it carries is a key of the object it sits in. Checked from the
/// registry alone, so it is complete: a name that is not a declared key — a typo, or one
/// renamed without its declaration — reaches the published schema as a property nothing
/// else mentions.
///
/// # Panics
///
/// If a variant carries a key the object's vocabulary does not declare.
pub fn assert_carried_keys_are_declared_keys<E: super::AuditEmitter>() {
    Registration::require_registry();
    let mut unknown = Vec::new();
    for reg in registrations(|reg| reg.emitter.name == E::NAME) {
        let Kind::Values { field, names, .. } = reg.kind else {
            continue;
        };
        let Some((_, _, vocabulary, _)) = FLATTENED.iter().find(|(f, _, _, _)| *f == field) else {
            continue;
        };
        // Scoped to the vocabulary holding this object's keys, but across every emitter: the
        // `action` and `entity` objects are Lakekeeper's, and the attribute lets no other
        // crate declare keys for them, so a product's own action carries Lakekeeper's keys.
        // Resolving against this emitter alone would find none of them.
        let object_keys = keys_of_object(registrations(|_| true), vocabulary);
        let owner = short_type_name((reg.type_name)());
        for name in names {
            for key in name.carries {
                if !object_keys.contains(key) {
                    unknown.push(format!("{owner}::{} carries `{key}`", name.text));
                }
            }
        }
    }
    assert!(
        unknown.is_empty(),
        "these variants carry a key the object does not declare:\n  {}\n\n\
         A key named here reaches the published schema as a property of that object, so it \
         has to be one the object's key vocabulary declares. Check the spelling, or add the \
         key to that vocabulary.",
        unknown.join("\n  ")
    );
}

/// The objects whose keys are properties: the vocabulary holding an object's keys, and the
/// definition of that object. Where the emitter declaring the keys does not own the object,
/// its schema says what its own keys hold in a definition of the same name.
const NESTED: [(&str, &str); 2] = [("context", "HandlerContext"), ("entity", "EntityRecord")];

/// Publish the keys this emitter declares for a nested object as that object's properties.
///
/// The object stays open — `additionalProperties` is untouched — because another product
/// contributes keys of its own, and the crate owning this definition has never heard of
/// them. A key of another product is typed by that product's own schema.
fn type_nested_keys(
    defs: &mut BTreeMap<String, Value>,
    regs: &[&Registration],
    key_schemas: &KeySchemas,
) {
    for (vocabulary, owner) in NESTED {
        let properties: Map<String, Value> = regs
            .iter()
            .filter_map(|reg| match reg.kind {
                Kind::Keys { object, names } if object == vocabulary => Some(names),
                _ => None,
            })
            .flatten()
            .filter_map(|name| {
                let spec = key_schemas.get(&(vocabulary, name.text))?.clone();
                Some((name.text.to_string(), spec))
            })
            .collect();
        if properties.is_empty() {
            continue;
        }
        // The object is shared, but its definition belongs to whoever declares the type. A
        // product that contributes keys to it and owns no such type says what its own keys
        // hold in a definition of the same name: each schema describes its own half, and a
        // consumer reading a record applies the schema of every emitter the record names.
        let def = defs.entry(owner.to_owned()).or_insert_with(|| {
            json!({
                "type": "object",
                "additionalProperties": true,
                "description": "The keys this product contributes to the record's `context` object. Another product's keys are described by its own schema.",
                "x-audit-kind": "part",
            })
        });
        if let Some(object) = def.as_object_mut() {
            let existing = object
                .entry("properties")
                .or_insert_with(|| Value::Object(Map::new()));
            if let Some(existing) = existing.as_object_mut() {
                existing.extend(properties);
            }
        }
    }
}

/// Say which `context` keys each value of a flattened field can bring with it.
///
/// An action is one flat object — its name under `action_name`, its context keys beside it —
/// so "`drop` carries `force` and `purge`" is a statement about that object, and `if`/`then`
/// is how JSON Schema states it. Written as ordinary conditionals rather than an extension
/// keyword, so a validator enforces it and a reader needs to know nothing about this log.
///
/// The object is left open: a branch adds `properties`, nothing forbids what no branch
/// names. An `action_name` from a newer release than the schema matches no branch and still
/// validates, which is the openness a value set already promises.
fn link_carried_keys(
    defs: &mut BTreeMap<String, Value>,
    regs: &[&Registration],
    key_schemas: &KeySchemas,
) {
    for (field, owner, vocabulary, default_type) in FLATTENED {
        let mut branches: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
        for reg in regs {
            let Kind::Values {
                field: f, names, ..
            } = reg.kind
            else {
                continue;
            };
            if f != field {
                continue;
            }
            for name in names {
                branches
                    .entry(name.text)
                    .or_default()
                    .extend(name.carries.iter().map(|k| (*k).to_string()));
            }
        }
        let conditionals: Vec<Value> = branches
            .into_iter()
            .filter(|(_, keys)| !keys.is_empty())
            .map(|(value, keys)| {
                let properties: Map<String, Value> =
                    keys.into_iter()
                        .map(|key| {
                            let spec = match key_schemas.get(&(vocabulary, key.as_str())) {
                                Some(schema) => schema.clone(),
                                None => default_type
                                    .map_or_else(|| json!({}), |ty| json!({ "type": ty })),
                            };
                            (key, spec)
                        })
                        .collect();
                json!({
                    "if": { "properties": { field: { "const": value } }, "required": [field] },
                    "then": { "properties": properties }
                })
            })
            .collect();
        if conditionals.is_empty() {
            continue;
        }
        // As above: a product whose actions carry keys says so in a definition of the same
        // name, holding only its own branches. `allOf` composes, so a consumer that applies
        // both schemas gets both halves without either knowing about the other.
        let def = defs.entry(owner.to_owned()).or_insert_with(|| {
            json!({
                "type": "object",
                "description": "Which `context` keys this product's actions carry. Another product's actions are described by its own schema.",
                "x-audit-kind": "part",
            })
        });
        if let Some(object) = def.as_object_mut() {
            object.insert("allOf".into(), json!(conditionals));
        }
    }
}

/// The name under `$defs` of the definition every record matches, and the document root.
pub const AUDIT_RECORD: &str = "AuditRecord";

/// Add [`AUDIT_RECORD`], the definition of any audit record, when `regs` declare shapes.
///
/// It holds what every record carries whatever its shape — the two stamps and `record_type`
/// — and routes on `record_type` to the shape that describes the rest, one `if`/`then` per
/// shape. A record of a type this schema does not know still validates against what it
/// shares with every record, as a value set's newer value does.
fn add_audit_record(defs: &mut BTreeMap<String, Value>, regs: &[&Registration]) {
    let shapes: Vec<(String, &str)> = regs
        .iter()
        .filter_map(|reg| match reg.kind {
            Kind::Shape { record_type } => Some((reg.schema_name?().to_string(), record_type)),
            _ => None,
        })
        .collect();
    if shapes.is_empty() {
        return;
    }
    let branches: Vec<Value> = shapes
        .iter()
        .map(|(def, record_type)| {
            json!({
                "if": {
                    "properties": { "record_type": { "const": record_type } },
                    "required": ["record_type"]
                },
                "then": { "$ref": format!("#/$defs/{def}") }
            })
        })
        .collect();
    defs.insert(
        AUDIT_RECORD.to_string(),
        json!({
            "type": "object",
            "description": "An audit record, whatever its shape. `record_type` names the shape that describes the rest of it.",
            "properties": {
                "event_source": {
                    "const": super::EVENT_SOURCE,
                    "description": "Marks the line as an audit record. Always `audit`."
                },
                "audit_format": {
                    "type": "string",
                    "pattern": "^[0-9]+\\.[0-9]+$",
                    "description": "The `MAJOR.MINOR` version of the record's shape. Compare each half as an integer."
                },
                "record_type": {
                    "type": "string",
                    "description": "Which shape the record has. A value this schema does not list is a newer record type."
                }
            },
            "required": ["event_source", "audit_format", "record_type"],
            "allOf": branches,
            "x-audit-kind": "part"
        }),
    );
}

/// An emitter's schema document: its definitions, and as its root the definition of any record
/// when it declares one.
fn document(
    title: &str,
    emitter: Value,
    extra: Option<(&str, &str)>,
    defs: Map<String, Value>,
) -> Value {
    let mut doc = Map::new();
    doc.insert("$schema".into(), json!(SCHEMA_DIALECT));
    doc.insert("title".into(), json!(title));
    if defs.contains_key(AUDIT_RECORD) {
        doc.insert("$ref".into(), json!(format!("#/$defs/{AUDIT_RECORD}")));
    }
    doc.insert("x-audit-emitter".into(), emitter);
    if let Some((key, value)) = extra {
        doc.insert(key.into(), json!(value));
    }
    doc.insert("$defs".into(), Value::Object(defs));
    Value::Object(doc)
}

/// Give a shape its `record_type`, pinned to the one value it carries.
///
/// The emitter stamps the field from the shape's attribute, so the struct the schema is
/// derived from holds no such field; it is added here, first, as it is on the line. For a
/// given shape it is a constant, not a choice from the vocabulary, and `const` says exactly
/// that, so a validator rejects a record checked against the wrong shape.
fn pin_record_type(shape: &mut Map<String, Value>, record_type: &str) {
    let property = json!({
        "description": format!("Names this record's shape. Always `{record_type}`."),
        "const": record_type,
    });
    // Replaced in place: with `preserve_order` a removed key would come back last.
    if let Some(Value::Object(properties)) = shape.get_mut("properties") {
        let mut first = Map::from_iter([("record_type".to_string(), property)]);
        first.append(properties);
        *properties = first;
    }
    if let Some(Value::Array(required)) = shape.get_mut("required") {
        required.insert(0, json!("record_type"));
    }
}

/// The crate schema of one crate: the definitions of the audit types it declares, for the
/// emitter it belongs to. Written by that crate's own unit tests, where its registrations are
/// certainly linked; committed as `audit-schema.json` at the crate root.
///
/// # Panics
///
/// If the crate registered nothing, or the registry is absent; see
/// [`Registration::require_registry`].
#[must_use]
pub fn crate_schema(defining_crate: &str) -> Value {
    Registration::require_registry();
    let regs = registrations(|r| r.defining_crate == defining_crate);
    let first = regs
        .first()
        .unwrap_or_else(|| panic!("crate `{defining_crate}` registered no audit types"));
    let emitter = first.emitter.name;
    let format = first.emitter.format;
    assert!(
        regs.iter().all(|r| r.emitter.name == emitter),
        "crate `{defining_crate}` registers types for more than one emitter"
    );
    let defs = definitions(&regs);
    document(
        &format!("Audit types declared by crate {defining_crate}"),
        json!({ "name": emitter, "format": format }),
        Some(("x-audit-crate", defining_crate)),
        defs.into_iter().collect(),
    )
}

/// Merge the committed crate schemas of one emitter into its schema.
///
/// # Panics
///
/// If the crate schemas name different emitters or formats, or two of them define the same
/// name differently.
#[must_use]
pub fn merge_crate_schemas(crate_schemas: &[Value]) -> Value {
    let first = crate_schemas.first().expect("at least one crate schema");
    let emitter = first["x-audit-emitter"].clone();
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    for fragment in crate_schemas {
        assert_eq!(
            fragment["x-audit-emitter"], emitter,
            "crate schema {} names another emitter or format",
            fragment["x-audit-crate"]
        );
        for (name, def) in fragment["$defs"].as_object().expect("$defs") {
            if let Some(existing) = defs.get(name) {
                assert_eq!(
                    existing, def,
                    "`{name}` is defined differently by two crate schemas ({})",
                    fragment["x-audit-crate"]
                );
            }
            defs.insert(name.clone(), def.clone());
        }
    }
    let name = emitter["name"].as_str().unwrap_or("?").to_string();
    document(
        &format!("Audit records emitted by {name}"),
        emitter,
        None,
        defs.into_iter().collect(),
    )
}

/// The type's name without module path or generics: the key it gets under `$defs`.
#[must_use]
pub fn short_type_name(full: &str) -> String {
    let tail = full.rsplit("::").next().unwrap_or(full);
    tail.split('<').next().unwrap_or(tail).to_string()
}

/// The schema of everything the emitter `emitter` can put on the wire, from the registrations
/// linked into this binary. Complete only where every crate of the emitter is linked and
/// referenced; the committed schema is assembled from crate schemas instead, see the module
/// docs.
///
/// # Panics
///
/// If nothing is registered for the emitter, or the registry is absent.
#[must_use]
pub fn audit_schema_for(emitter: &str) -> Value {
    Registration::require_registry();
    let regs = registrations(|r| r.emitter.name == emitter);
    let first = regs
        .first()
        .unwrap_or_else(|| panic!("no audit types registered for emitter `{emitter}`"));
    let format = first.emitter.format;
    let defs = definitions(&regs);
    document(
        &format!("Audit records emitted by {emitter}"),
        json!({ "name": emitter, "format": format }),
        None,
        defs.into_iter().collect(),
    )
}

/// The schema as a pretty-printed document with a trailing newline, as committed.
///
/// # Panics
///
/// If the value does not serialize, which a schema built by this module always does.
#[must_use]
pub fn render(schema: &Value) -> String {
    let mut text = serde_json::to_string_pretty(schema).expect("a schema serializes");
    text.push('\n');
    text
}

/// The crate schema file of a crate: `audit-schema.json` at its root.
#[must_use]
pub fn crate_schema_path(manifest_dir: &str) -> std::path::PathBuf {
    std::path::Path::new(manifest_dir).join("audit-schema.json")
}

/// The environment variable that switches the crate schema and schema tests from comparing to
/// writing.
pub const UPDATE_ENV: &str = "LAKEKEEPER_UPDATE_AUDIT_SCHEMA";

/// Assert that the committed crate schema of `defining_crate` equals what its registry
/// generates, or write it when [`UPDATE_ENV`] is set. For use in that crate's own tests, so the
/// registrations are certainly linked.
///
/// # Panics
///
/// If the committed crate schema is missing or stale. That is the point: this is for use in
/// tests.
pub fn assert_crate_schema_committed(defining_crate: &str, manifest_dir: &str) {
    let path = crate_schema_path(manifest_dir);
    let generated = render(&crate_schema(defining_crate));
    if std::env::var_os(UPDATE_ENV).is_some() {
        std::fs::write(&path, &generated)
            .unwrap_or_else(|e| panic!("writing {}: {e}", path.display()));
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the committed crate schema {}: {e}\n\nGenerate it with `just update-audit-schema`.",
            path.display()
        )
    });
    assert!(
        committed == generated,
        "the committed crate schema {} is not what the registry generates. Run `just update-audit-schema` and review the diff: it is what a consumer of the audit log will see.",
        path.display()
    );
}

/// Assert that no two vocabularies keying the same object declare the same key.
///
/// The `context` map of an authorization record is one flat object, and `keys_of =
/// "context"` is the one vocabulary form open to an emitter outside this repository. So two
/// products can reach the same key of the same object. One key, one meaning: a second
/// declaration is a second meaning at one path in one record, and whichever handler writes
/// last decides which of them a consumer sees.
///
/// Reads the whole registry rather than one crate's, so it sees every vocabulary linked into
/// the binary that runs it. Run from an emitting crate's own tests it therefore compares that
/// crate's keys against Lakekeeper's, which is the pairing that can clash.
///
/// A name reused at a *different* path is not this. `actor.principal` and `context.principal`
/// are two fields named for where they sit, which is why the reference tells a consumer to
/// address fields by path.
///
/// # Panics
///
/// If one object has the same key from two vocabularies.
pub fn assert_no_object_declares_a_key_twice() {
    Registration::require_registry();
    let mut owners: BTreeMap<(&str, &str), Vec<String>> = BTreeMap::new();
    for reg in registrations(|_| true) {
        let Kind::Keys { object, .. } = reg.kind else {
            continue;
        };
        let owner = short_type_name((reg.type_name)());
        for key in reg.kind.names().iter().map(|name| name.text) {
            owners.entry((object, key)).or_default().push(owner.clone());
        }
    }
    let clashes: Vec<String> = owners
        .iter()
        .filter(|(_, declared_by)| declared_by.len() > 1)
        .map(|((object, key), declared_by)| {
            format!(
                "{object}: `{key}` is declared by {}",
                declared_by.join(" and ")
            )
        })
        .collect();
    assert!(
        clashes.is_empty(),
        "these keys are declared twice for one object:\n  {}\n\n\
         A key names one thing. Two vocabularies declaring it for the same object put two \
         meanings at one path in one record, and the handler that writes last decides which \
         one a consumer sees. Rename one of them, or have the second use the first rather \
         than declaring its own.",
        clashes.join("\n  ")
    );
}

/// Every value set in `schema` is pointed at by a field, so none is published with nothing
/// saying where its values appear.
///
/// The sets of `action_name`, `operation` and `outcome` are exempt: those fields hold values
/// from whichever product wrote the record, so they are open and point at no one set. So is
/// `record_type`, which each shape pins to its one value.
///
/// # Panics
///
/// If a value set no field references.
pub fn assert_every_value_set_is_referenced(schema: &Value) {
    const OPEN_FIELDS: [&str; 4] = ["action_name", "operation", "outcome", "record_type"];
    fn refs(value: &Value, out: &mut BTreeSet<String>) {
        match value {
            Value::Object(map) => {
                if let Some(target) = map.get("$ref").and_then(Value::as_str) {
                    out.insert(target.rsplit('/').next().unwrap_or(target).to_string());
                }
                map.values().for_each(|child| refs(child, out));
            }
            Value::Array(items) => items.iter().for_each(|child| refs(child, out)),
            _ => {}
        }
    }
    let defs = schema["$defs"].as_object().expect("a schema has `$defs`");
    let mut referenced = BTreeSet::new();
    refs(&Value::Object(defs.clone()), &mut referenced);
    let unreferenced: Vec<&String> = defs
        .iter()
        .filter(|(_, def)| def["x-audit-kind"] == "enum" && def.get("x-audit-field").is_some())
        .filter(|(_, def)| {
            !OPEN_FIELDS
                .iter()
                .any(|field| def["x-audit-field"] == *field)
        })
        .map(|(name, _)| name)
        .filter(|name| !referenced.contains(name.as_str()))
        .collect();
    assert!(
        unreferenced.is_empty(),
        "these value sets are published and no field points at them: {unreferenced:?}. A field \
         holding one of their values is a `Wire<Vocabulary>`, which is what references the set; \
         one holding a plain string leaves the set unused."
    );
}

/// Every Rust source under `dir`, read into `out`.
fn rust_sources(dir: &std::path::Path, out: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "target") {
                continue;
            }
            rust_sources(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs")
            && let Ok(text) = std::fs::read_to_string(&path)
        {
            out.push(text);
        }
    }
}

/// A name with its separators and case removed, so two spellings of one name compare equal.
///
/// The source names a variant, `DryRun`; the registry names what that variant puts on the
/// wire, `dry_run`. Both reduce to `dryrun`. A variant the attribute renames to something
/// else entirely still differs, which is the case worth a human reading it.
fn normalized(name: &str) -> String {
    name.chars()
        .filter(char::is_ascii_alphanumeric)
        .map(|c| c.to_ascii_lowercase())
        .collect()
}

/// The identifier following the first `prefix` in `block`, or `None` when there is none.
fn identifier_after(block: &str, prefix: &str) -> Option<String> {
    let at = block.find(prefix)? + prefix.len();
    let identifier: String = block[at..]
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    (!identifier.is_empty()).then_some(identifier)
}

/// Every `context` key an emitter declares is pushed by some call under `crates_dir`.
///
/// A key vocabulary is pinned by the schema: rename or drop a name and the format moves, and
/// the checker reports it. A `push_extra_context` call deleted in a refactor is invisible
/// there. The key leaves the wire, the enum that declares it stays, the schema diff is empty,
/// and a field a consumer reads is gone with nothing to announce it. This reads the registry
/// for the keys and the source for the pushes.
///
/// The source is read rather than a record captured because these keys ride on a record their
/// own crate does not assemble: an emitter outside Lakekeeper pushes keys onto an
/// authorization record that Lakekeeper stamps, so that crate has no record of its own to
/// capture them from.
///
/// One push site is enough to pass. A key pushed from two places passes while either remains.
///
/// # Panics
///
/// If a declared key has no push site, or if the scan finds no sources or no push sites,
/// which means it is pointed at the wrong tree.
pub fn assert_every_context_key_is_pushed<E: super::AuditEmitter>(crates_dir: &std::path::Path) {
    Registration::require_registry();

    let mut declared: BTreeMap<String, Vec<&'static str>> = BTreeMap::new();
    for reg in registrations(|reg| reg.emitter.name == E::NAME) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        if object != "context" {
            continue;
        }
        declared
            .entry(short_type_name((reg.type_name)()))
            .or_default()
            .extend(names.iter().map(|name| name.text));
    }
    assert!(
        !declared.is_empty(),
        "emitter `{}` has no `context` key vocabulary in this registry, so either it declares          none or the crate that declares one is not linked into this test binary.",
        E::NAME
    );

    let mut sources = Vec::new();
    rust_sources(crates_dir, &mut sources);
    assert!(
        sources.len() > 10,
        "only {} Rust sources under {}, so this is scanning the wrong tree",
        sources.len(),
        crates_dir.display()
    );

    let mut pushed: BTreeSet<(String, String)> = BTreeSet::new();
    for text in &sources {
        for (at, _) in text.match_indices("push_extra_context") {
            // The call, bounded generously: the key is its first argument, and the longest of
            // these calls wraps over a few lines. Bounded in CHARACTERS: a byte slice that
            // lands inside a multi-byte character panics, and these sources are full of em
            // dashes.
            let block: String = text[at..].chars().take(400).collect();
            for vocabulary in declared.keys() {
                if let Some(variant) = identifier_after(&block, &format!("{vocabulary}::")) {
                    pushed.insert((vocabulary.clone(), normalized(&variant)));
                }
            }
        }
    }
    assert!(
        !pushed.is_empty(),
        "no `push_extra_context` call under {} names a declared key, so this is scanning the \
         wrong tree",
        crates_dir.display()
    );

    let mut missing: Vec<String> = Vec::new();
    for (vocabulary, keys) in &declared {
        for key in keys {
            if !pushed.contains(&(vocabulary.clone(), normalized(key))) {
                missing.push(format!("{vocabulary}::{key}"));
            }
        }
    }
    assert!(
        missing.is_empty(),
        "these `context` keys are declared and pushed nowhere:\n  {}\n\n\
         A key nothing pushes is a field the schema promises and no record carries. Push it, \
         or drop it from the vocabulary and write the fragment its removal owes.",
        missing.join("\n  ")
    );
}
