//! One JSON Schema per emitter, generated from the registry of the running binary.
//!
//! The schema is the ground truth of an emitter's audit format: every registered part, context
//! and vocabulary enum appears under `$defs`, with the doc comments as descriptions. It is
//! generated by a test in a crate that links every contributing crate, committed at
//! `audit-format/schema.json`, validated against by the tests, diffed across the merge base by
//! the format checker, and published to the documentation site.
//!
//! A crate cannot see another crate's registrations unless the linker keeps that crate's
//! objects, which it does only when something references them. So the schema is assembled in
//! two steps that need no linker cooperation: every crate that declares audit types commits a
//! **crate schema**, the definitions of its own types, written by its own unit tests
//! ([`crate_schema`]); and one test in a crate that sees every crate schema file merges them
//! per emitter into the committed schema ([`merge_crate_schemas`]).
//!
//! Two properties make the extra step worth it, and both are lost by generating the schema in
//! one place. A crate's schema is written by that crate's own test binary, where its
//! registrations are certainly linked, so a definition cannot go missing without a test
//! failing; and the file sits in the crate, so a pull request touching one crate shows that
//! crate's schema diff next to the change that caused it.
//!
//! Available under `test-utils`, so the tests of other emitting crates generate their crate
//! schema with this implementation. Debug builds only, like the registry it reads: see
//! [`Registration::require_registry`].

use std::collections::{BTreeMap, BTreeSet};

use schemars::{SchemaGenerator, generate::SchemaSettings};
use serde::Serialize;
use serde_json::{Map, Value, json};

use super::part::{Kind, Registration};

/// The JSON Schema dialect every audit schema declares.
pub const SCHEMA_DIALECT: &str = "https://json-schema.org/draft/2020-12/schema";

/// The registrations that describe a format, filtered by `keep`.
///
/// The probe types declared inside `#[cfg(test)] mod tests` are left out: they exist to
/// exercise the attribute and reach no record, so a schema that listed them would promise
/// shapes no consumer ever meets. They are recognised by `::tests::` in the type path, which
/// is where a type declared in such a module always sits.
fn registrations(keep: impl Fn(&Registration) -> bool) -> Vec<&'static Registration> {
    let mut regs: Vec<&Registration> = Registration::all()
        .filter(|r| !(r.type_name)().contains("::tests::"))
        .filter(|r| keep(r))
        .collect();
    regs.sort_by_key(|r| (r.type_name)());
    regs
}

/// Strip `null` from every optional property, in place and at every depth.
///
/// A field with no value is left out of the record; nothing emits `null`. The schema
/// generator does not know that — it renders `Option<T>` as "T or null" — so without this
/// the schema would promise a shape the emitter cannot produce, and a consumer would write a
/// parser for a value they will never see. A property that is required keeps whatever it
/// has: `null` there would be a real value, not an absence.
fn drop_null_from_optionals(schema: &mut Value) {
    if let Some(object) = schema.as_object_mut() {
        let required: Vec<&str> = object
            .get("required")
            .and_then(Value::as_array)
            .map(|r| r.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let optional: Vec<String> = object
            .get("properties")
            .and_then(Value::as_object)
            .map(|p| {
                p.keys()
                    .filter(|name| !required.contains(&name.as_str()))
                    .cloned()
                    .collect()
            })
            .unwrap_or_default();
        if let Some(properties) = object.get_mut("properties").and_then(Value::as_object_mut) {
            for name in optional {
                if let Some(spec) = properties.get_mut(&name) {
                    drop_null_alternative(spec);
                }
            }
        }
        for value in object.values_mut() {
            drop_null_from_optionals(value);
        }
    } else if let Some(array) = schema.as_array_mut() {
        for value in array {
            drop_null_from_optionals(value);
        }
    }
}

/// Remove the `null` alternative from one property, in whichever of the two forms the
/// generator wrote it: a type list for a scalar, an `anyOf` branch for a type that has a
/// definition of its own.
fn drop_null_alternative(spec: &mut Value) {
    let Some(object) = spec.as_object_mut() else {
        return;
    };
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        let kept: Vec<Value> = kinds.iter().filter(|k| *k != "null").cloned().collect();
        if kept.len() != kinds.len() {
            let kept = if let [only] = kept.as_slice() {
                only.clone()
            } else {
                Value::Array(kept)
            };
            object.insert("type".into(), kept);
        }
    }
    let Some(branches) = object.get("anyOf").and_then(Value::as_array) else {
        return;
    };
    let kept: Vec<Value> = branches
        .iter()
        .filter(|branch| branch["type"] != "null")
        .cloned()
        .collect();
    // Unchanged, or nothing but `null` — which would leave the property with no schema at
    // all, so it stays as the generator wrote it.
    if kept.len() == branches.len() || kept.is_empty() {
        return;
    }
    // One alternative left, and it is an object, so it is the property's schema and takes the
    // place of the branch list. Keys the property already carries win: `description` there is
    // the field's own doc comment, not the referenced type's. Anything else keeps its branch
    // list, because removing it would leave the property with no schema at all.
    match kept.as_slice() {
        [only] if only.is_object() => {
            object.remove("anyOf");
            for (key, value) in only.as_object().expect("checked by the guard") {
                object.entry(key.clone()).or_insert_with(|| value.clone());
            }
        }
        _ => {
            object.insert("anyOf".into(), Value::Array(kept));
        }
    }
}

/// Insert `map` under `extension` on a vocabulary's definition, or nothing when it is empty.
fn add_key_map<V: Serialize>(def: &mut Value, extension: &str, map: &BTreeMap<&str, V>) {
    if !map.is_empty()
        && let Some(object) = def.as_object_mut()
    {
        object.insert(extension.to_owned(), json!(map));
    }
}

/// The shape each key's value carries, for the keys that declare one.
fn key_shapes(reg: &Registration) -> BTreeMap<&str, Value> {
    reg.kind
        .names()
        .iter()
        .filter_map(|name| {
            name.shape
                .map(|shape| (name.text, json!({ "$ref": format!("#/$defs/{shape}") })))
        })
        .collect()
}

/// The definitions the registrations contribute, plus every type they reference.
///
/// # Panics
///
/// If two registered types want the same `$defs` name. A definition is keyed by the type's
/// short name, so two types of one emitter called `Context` in different modules would
/// otherwise silently become one, and whichever lost would vanish from the schema while its
/// records kept being emitted.
fn definitions(regs: &[&Registration]) -> BTreeMap<String, Value> {
    let mut generator = SchemaGenerator::new(SchemaSettings::draft2020_12());
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    let mut claimed: BTreeMap<String, &'static str> = BTreeMap::new();
    let mut claim = |name: &str, type_name: &'static str| {
        if let Some(other) = claimed.insert(name.to_owned(), type_name) {
            assert_eq!(
                other, type_name,
                "`{name}` is the schema name of two registered types, {other} and \
                 {type_name}. One would replace the other in the schema. Rename one of them."
            );
        }
    };
    for reg in regs {
        match reg.kind {
            Kind::Part | Kind::Context | Kind::Shape { .. } => {
                let (Some(schema), Some(name)) = (reg.schema, reg.schema_name) else {
                    continue;
                };
                let mut schema = schema(&mut generator).to_value();
                if let Some(object) = schema.as_object_mut() {
                    object.insert("x-audit-kind".into(), json!(reg.kind.as_str()));
                    if let Kind::Shape { record_type } = reg.kind {
                        object.insert("x-audit-record-type".into(), json!(record_type));
                        pin_record_type(object, record_type);
                    }
                }
                let name = name().to_string();
                claim(&name, (reg.type_name)());
                defs.insert(name, schema);
            }
            Kind::Values { .. } | Kind::Keys { .. } => {
                // A name is a string in a list, so JSON Schema gives it nowhere to carry its
                // own description. This map is where a variant's doc comment reaches a
                // consumer; without it the schema lists the names and explains none of them.
                let descriptions: BTreeMap<&str, &str> = reg
                    .kind
                    .names()
                    .iter()
                    .filter(|name| !name.doc.is_empty())
                    .map(|name| (name.text, name.doc))
                    .collect();
                let mut names: Vec<&str> = reg.kind.names().iter().map(|n| n.text).collect();
                names.sort_unstable();
                // A value vocabulary names the field its values fill; a key vocabulary names
                // the object its variants are keys of. Different extensions, because a
                // consumer and the format check both act on the difference: a new value
                // changes no format, a new key adds a field.
                let place = match reg.kind {
                    Kind::Keys { .. } => "x-audit-keys-of",
                    _ => "x-audit-field",
                };
                let mut def = json!({
                    "type": "string",
                    "enum": names,
                    "x-audit-kind": reg.kind.as_str(),
                    place: reg.kind.wire_place(),
                });
                // What a vocabulary says about its own names, keyed by name. These sit on
                // the vocabulary and not on the object the names belong to, because the
                // object is shared: `context` takes keys from every emitter, and the crate
                // that declares the object has never heard of the others. A consumer reads
                // what a key holds from the schema of whoever declared the key.
                add_key_map(&mut def, "x-audit-descriptions", &descriptions);
                add_key_map(&mut def, "x-audit-key-shapes", &key_shapes(reg));
                let name = short_type_name((reg.type_name)());
                claim(&name, (reg.type_name)());
                defs.insert(name, def);
            }
        }
    }
    // Types the parts reference but that are not registered themselves, if any, and every
    // registered type the generator chose to reference rather than inline. An unregistered
    // one still reaches a consumer, so it is kinded here too: the kind is how a reader of the
    // schema tells a value set from an object, and a definition without one says neither.
    for (name, schema) in generator.take_definitions(true) {
        let mut schema = schema;
        if let Some(object) = schema.as_object_mut() {
            let values = object.contains_key("enum")
                || object
                    .get("oneOf")
                    .and_then(Value::as_array)
                    .is_some_and(|variants| variants.iter().all(|v| v.get("const").is_some()));
            object
                .entry("x-audit-kind")
                .or_insert_with(|| json!(if values { "enum" } else { "part" }));
        }
        defs.entry(name).or_insert(schema);
    }
    for schema in defs.values_mut() {
        drop_null_from_optionals(schema);
    }
    link_value_sets(&mut defs, regs);
    link_carried_keys(&mut defs, regs);
    type_nested_keys(&mut defs, regs);
    defs
}

/// The objects whose keys sit beside the value that names them, rather than nested under it.
///
/// Each entry is the field carrying that value, the object it sits in, and the type its keys
/// hold when they declare none: an entity field's value is a `String` in the type that
/// carries it, while an action's is a three-way choice each key has to declare.
/// The flattened pairs: the wire field naming the thing, the schema definition it sits in,
/// the `keys_of` vocabulary holding that object's keys, and the type a key takes when it
/// declares none.
const FLATTENED: [(&str, &str, &str, Option<&str>); 2] = [
    ("action_name", "ActionRecord", "action", None),
    ("entity_type", "EntityRecord", "entity", Some("string")),
];

/// Every key a vocabulary declares for `object`.
fn keys_of_object(regs: Vec<&'static Registration>, object: &str) -> BTreeSet<&'static str> {
    regs.into_iter()
        .filter_map(|reg| match reg.kind {
            Kind::Keys { object: o, names } if o == object => Some(names),
            _ => None,
        })
        .flatten()
        .map(|name| name.text)
        .collect()
}

/// Every `context` key is written with the type it declares.
///
/// The type a key holds is declared on the key — `#[audit(value = "array")]` — because no key
/// in this log is written two ways, so saying it once is shorter and harder to get wrong than
/// repeating it in every branch. That makes it a claim about code elsewhere, and this is what
/// holds the claim to it: the builder a key is written with pins its type, and the two must
/// agree.
///
/// Read from the source because the fact lives at the call site. A key written through
/// `context_pairs` names its type in the `ContextValue` beside it instead.
///
/// # Panics
///
/// If a key's declared type is not the one it is written with, if a key declares none, or if
/// the scan finds no call sites, which means it is reading the wrong tree.
pub fn assert_declared_key_types_match_the_code<E: super::AuditEmitter>(
    crates_dir: &std::path::Path,
) {
    Registration::require_registry();

    let declared = declared_key_types::<E>();
    assert_carried_keys_are_declared_keys::<E>();
    let written = key_types_written_in_source(crates_dir);

    let mut wrong = Vec::new();
    for ((object, key), ty) in &declared {
        let Some(seen) = written.get(&(*object, normalized(key))) else {
            continue; // declared but written nowhere: `every_declared_context_key_is_pushed`
        };
        if !seen.contains(ty) {
            wrong.push(format!(
                "`{key}` of `{object}` declares `{ty}` and is written as {}",
                seen.iter().copied().collect::<Vec<_>>().join(" and ")
            ));
        }
    }
    assert!(
        wrong.is_empty(),
        "these keys are declared as one type and written as another:\n  {}\n\n\
         The declared type reaches the published schema, so a consumer validates against it. \
         Change the declaration to match the builder, or the builder to match the \
         declaration — they describe one thing.",
        wrong.join("\n  ")
    );
}

/// The declared value type of every key of a flattened object, from the registry.
///
/// # Panics
///
/// If a key of an `action` declares none.
fn declared_key_types<E: super::AuditEmitter>()
-> BTreeMap<(&'static str, &'static str), &'static str> {
    // Keyed by the object the key belongs to: one name may be a key of two objects and mean
    // a different thing in each, so a type declared for one says nothing about the other.
    let mut declared: BTreeMap<(&str, &str), &str> = BTreeMap::new();
    let mut undeclared = Vec::new();
    for reg in registrations(|reg| reg.emitter_name == E::NAME) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        for name in names {
            match name.value_type {
                Some(ty) => {
                    declared.insert((object, name.text), ty);
                }
                // An entity field's value is a `String` in the type that carries it, so
                // the compiler already says what it is. Every other object's keys are
                // written through a builder that picks the type, so they say which.
                None if matches!(object, "action" | "context") => {
                    undeclared.push(name.text.to_string());
                }
                None => {}
            }
        }
    }
    assert!(
        undeclared.is_empty(),
        "these keys declare no value type:\n  {}\n\n\
         A key of a flattened object sits beside its action or entity on the wire, so a \
         consumer needs its type. Add `#[audit(value = \"string\"|\"array\"|\"object\")]`, \
         matching the builder the key is written with.",
        undeclared.join("\n  ")
    );
    declared
}

/// Every key a variant says it carries is a key of the object it sits in. Checked from the
/// registry alone, so it is complete: a name that is not a declared key — a typo, or one
/// renamed without its declaration — reaches the published schema as a property nothing
/// else mentions.
///
/// # Panics
///
/// If a variant carries a key the object's vocabulary does not declare.
fn assert_carried_keys_are_declared_keys<E: super::AuditEmitter>() {
    let mut unknown = Vec::new();
    for reg in registrations(|reg| reg.emitter_name == E::NAME) {
        let Kind::Values { field, names } = reg.kind else {
            continue;
        };
        let Some((_, _, vocabulary, _)) = FLATTENED.iter().find(|(f, _, _, _)| *f == field) else {
            continue;
        };
        // Scoped to the vocabulary holding this object's keys, but across every emitter: the
        // `action` and `entity` objects are Lakekeeper's, and the attribute lets no other
        // crate declare keys for them, so a product's own action carries Lakekeeper's keys.
        // Resolving against this emitter alone would find none of them.
        let object_keys = keys_of_object(registrations(|_| true), vocabulary);
        let owner = short_type_name((reg.type_name)());
        for name in names {
            for key in name.carries {
                if !object_keys.contains(key) {
                    unknown.push(format!("{owner}::{} carries `{key}`", name.text));
                }
            }
        }
    }
    assert!(
        unknown.is_empty(),
        "these variants carry a key the object does not declare:\n  {}\n\n\
         A key named here reaches the published schema as a property of that object, so it \
         has to be one the object's key vocabulary declares. Check the spelling, or add the \
         key to that vocabulary.",
        unknown.join("\n  ")
    );
}

/// The value types each context key is actually written with, read from the source because
/// the fact lives at the call site.
///
/// # Panics
///
/// If the scan finds almost no call sites, which means it is reading the wrong tree.
fn key_types_written_in_source(
    crates_dir: &std::path::Path,
) -> BTreeMap<(&'static str, String), BTreeSet<&'static str>> {
    /// The push that puts a key on the record's own `context` object. The variants spell
    /// the type they write, so the call site says it without a separate declaration.
    const PUSH: &str = "push_extra_context";

    // The key enums to look for at a call site, taken from the registry rather than named
    // here, so a crate that declares its own `context` keys is read by the same pass.
    let vocabularies: Vec<(&str, String)> = registrations(|_| true)
        .iter()
        .filter_map(|reg| match reg.kind {
            Kind::Keys { object, .. } => {
                Some((object, format!("{}::", short_type_name((reg.type_name)()))))
            }
            _ => None,
        })
        .collect();
    let for_object = |want: &str| -> Vec<String> {
        vocabularies
            .iter()
            .filter(|(object, _)| *object == want)
            .map(|(_, prefix)| prefix.clone())
            .collect()
    };
    let action_prefixes = for_object("action");
    let context_prefixes = for_object("context");

    let mut sources = Vec::new();
    rust_sources(crates_dir, &mut sources);
    let builders = [
        ("context_string", "string"),
        ("context_bool", "boolean"),
        ("context_integer", "integer"),
        ("context_list", "array"),
        ("context_map", "object"),
    ];
    let values = [
        ("ContextValue::String", "string"),
        ("ContextValue::Bool", "boolean"),
        ("ContextValue::Integer", "integer"),
        ("ContextValue::List", "array"),
        ("ContextValue::Map", "object"),
        ("ContextValue::Object", "object"),
    ];

    // Keyed by the object, like the declarations it is compared against: the two key
    // vocabularies may spell the same name for different objects.
    let mut written: BTreeMap<(&'static str, String), BTreeSet<&'static str>> = BTreeMap::new();
    for text in &sources {
        for (builder, ty) in builders {
            for (at, _) in text.match_indices(builder) {
                let block: String = text[at..].chars().take(120).collect();
                for prefix in &action_prefixes {
                    if let Some(variant) = identifier_after(&block, prefix) {
                        written
                            .entry(("action", normalized(&variant)))
                            .or_default()
                            .insert(ty);
                    }
                }
            }
        }
        // A key of the record's own `context` object is written by the push it is handed
        // to, which names the type in its own name.
        for (at, _) in text.match_indices(PUSH) {
            let ty = match &text[at + PUSH.len()..] {
                rest if rest.starts_with("_bool") => "boolean",
                rest if rest.starts_with("_object") => "object",
                // The plain push takes a string; anything else here is the declaration of
                // one of these functions, not a call to it.
                rest if rest.starts_with('(') => "string",
                _ => continue,
            };
            let block: String = text[at..].chars().take(160).collect();
            for prefix in &context_prefixes {
                if let Some(variant) = identifier_after(&block, prefix) {
                    written
                        .entry(("context", normalized(&variant)))
                        .or_default()
                        .insert(ty);
                }
            }
        }
        // A key built as a pair names its type in the value constructed beside it.
        for prefix in &action_prefixes {
            for (at, _) in text.match_indices(prefix.as_str()) {
                let block: String = text[at..].chars().take(160).collect();
                let Some(variant) = identifier_after(&block, prefix) else {
                    continue;
                };
                for (value, ty) in values {
                    if block.contains(value) {
                        written
                            .entry(("action", normalized(&variant)))
                            .or_default()
                            .insert(ty);
                    }
                }
            }
        }
    }
    assert!(
        written.len() >= 10,
        "only {} keys found at a call site, so this is scanning the wrong tree",
        written.len()
    );
    written
}

/// The nested key-value objects of a record: the vocabulary holding an object's keys, and
/// the definition of that object where the emitter declaring the keys also owns the object.
const NESTED: [(&str, &str); 1] = [("context", "HandlerContext")];

/// Type the keys of a nested object that this emitter declares.
///
/// The object stays open — `additionalProperties` is untouched — because another product
/// contributes keys of its own, and the crate owning this definition has never heard of
/// them. A key of another product is typed by the branches of that product's own schema.
fn type_nested_keys(defs: &mut BTreeMap<String, Value>, regs: &[&Registration]) {
    for (vocabulary, owner) in NESTED {
        let properties: Map<String, Value> = regs
            .iter()
            .filter_map(|reg| match reg.kind {
                Kind::Keys { object, names } if object == vocabulary => Some(names),
                _ => None,
            })
            .flatten()
            .filter_map(|name| {
                let mut spec = match (name.shape, name.value_type) {
                    (Some(shape), _) => json!({ "$ref": format!("#/$defs/{shape}") }),
                    (None, Some(ty)) => json!({ "type": ty }),
                    (None, None) => return None,
                };
                // The key's own doc comment: a property of a published object carries its
                // description like any other, and a test holds every property to that.
                if !name.doc.is_empty()
                    && let Some(object) = spec.as_object_mut()
                {
                    object.insert("description".into(), json!(name.doc));
                }
                Some((name.text.to_string(), spec))
            })
            .collect();
        if properties.is_empty() {
            continue;
        }
        // The object is shared, but its definition belongs to whoever declares the type. A
        // product that contributes keys to it and owns no such type says what its own keys
        // hold in a definition of the same name: each schema describes its own half, and a
        // consumer reading a record applies the schema of every emitter the record names.
        let def = defs.entry(owner.to_owned()).or_insert_with(|| {
            json!({
                "type": "object",
                "additionalProperties": true,
                "description": "The keys this product contributes to the record's `context`                                 object. Another product's keys are described by its own schema.",
            })
        });
        if let Some(object) = def.as_object_mut() {
            object.insert("properties".into(), Value::Object(properties));
        }
    }
}

/// Say which `context` keys each value of a flattened field can bring with it.
///
/// An action is one flat object — its name under `action_name`, its context keys beside it —
/// so "`drop` carries `force` and `purge`" is a statement about that object, and `if`/`then`
/// is how JSON Schema states it. Written as ordinary conditionals rather than an extension
/// keyword, so a validator enforces it and a reader needs to know nothing about this log.
///
/// The object is left open: a branch adds `properties`, nothing forbids what no branch
/// names. An `action_name` from a newer release than the schema matches no branch and still
/// validates, which is the openness a value set already promises.
fn link_carried_keys(defs: &mut BTreeMap<String, Value>, regs: &[&Registration]) {
    // Which object a field belongs to, for the two flattened pairs this log has.

    // A key's type is a property of the key: no key in this log is written as two types, so
    // it is declared once on the key vocabulary and looked up here rather than repeated in
    // every branch that names it.
    // Keyed by the object too: a key names one thing per object, not across all of them, so
    // the same name may be declared for an `action` and for an `entity` and mean two
    // different things. `assert_no_object_declares_a_key_twice` allows exactly that.
    let mut key_types: BTreeMap<(&str, &str), &str> = BTreeMap::new();
    // The closed set a key's value is drawn from, where it is drawn from one. The vocabulary
    // already has a definition in this document, so the key points at it instead of
    // publishing the set a second time.
    let mut key_values: BTreeMap<(&str, &str), &str> = BTreeMap::new();
    // Across every emitter, unlike the branches below: the `action` and `entity` objects are
    // Lakekeeper's and no other crate may declare keys for them, so a product's own action
    // carries Lakekeeper's keys and must read their types from Lakekeeper's vocabulary.
    for reg in registrations(|_| true) {
        if let Kind::Keys { object, names } = reg.kind {
            for name in names {
                if let Some(ty) = name.value_type {
                    key_types.insert((object, name.text), ty);
                }
                if let Some(vocabulary) = name.values {
                    key_values.insert((object, name.text), vocabulary);
                }
            }
        }
    }

    for (field, owner, vocabulary, default_type) in FLATTENED {
        let mut branches: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
        for reg in regs {
            let Kind::Values { field: f, names } = reg.kind else {
                continue;
            };
            if f != field {
                continue;
            }
            for name in names {
                branches
                    .entry(name.text)
                    .or_default()
                    .extend(name.carries.iter().map(|k| (*k).to_string()));
            }
        }
        let conditionals: Vec<Value> = branches
            .into_iter()
            .filter(|(_, keys)| !keys.is_empty())
            .map(|(value, keys)| {
                let properties: Map<String, Value> = keys
                    .into_iter()
                    .map(|key| {
                        let ty = key_types
                            .get(&(vocabulary, key.as_str()))
                            .copied()
                            .or(default_type);
                        let drawn_from = key_values
                            .get(&(vocabulary, key.as_str()))
                            .map(|name| json!({ "$ref": format!("#/$defs/{name}") }));
                        // An array says what it holds, whether or not that is a closed set:
                        // every one of them holds strings, and saying so costs nothing.
                        let spec = match (ty, drawn_from) {
                            (Some("array"), Some(item)) => {
                                json!({ "type": "array", "items": item })
                            }
                            (Some("array"), None) => {
                                json!({ "type": "array", "items": { "type": "string" } })
                            }
                            (_, Some(item)) => item,
                            (Some(ty), None) => json!({ "type": ty }),
                            (None, None) => json!({}),
                        };
                        (key, spec)
                    })
                    .collect();
                json!({
                    "if": { "properties": { field: { "const": value } }, "required": [field] },
                    "then": { "properties": properties }
                })
            })
            .collect();
        if conditionals.is_empty() {
            continue;
        }
        // As above: a product whose actions carry keys says so in a definition of the same
        // name, holding only its own branches. `allOf` composes, so a consumer that applies
        // both schemas gets both halves without either knowing about the other.
        let def = defs.entry(owner.to_owned()).or_insert_with(|| {
            json!({
                "type": "object",
                "description": "Which `context` keys this product's actions carry. Another                                 product's actions are described by its own schema.",
            })
        });
        if let Some(object) = def.as_object_mut() {
            object.insert("allOf".into(), json!(conditionals));
        }
    }
}

/// Pin a shape's `record_type` to the one value it carries.
///
/// The field is the one a consumer routes on, and for a given shape it is a constant, not a
/// choice from the vocabulary. `const` says exactly that, so a validator rejects a record
/// checked against the wrong shape instead of accepting any of the three.
fn pin_record_type(shape: &mut Map<String, Value>, record_type: &str) {
    let Some(property) = shape
        .get_mut("properties")
        .and_then(Value::as_object_mut)
        .and_then(|properties| properties.get_mut("record_type"))
        .and_then(Value::as_object_mut)
    else {
        return;
    };
    property.remove("type");
    property.insert("const".into(), json!(record_type));
}

/// Point every field that holds a closed set of values at the definition listing them.
///
/// A field's type is `WireStr` or a string stand-in, so the generator writes `"type":
/// "string"` and the value set sits in `$defs` with nothing referring to it. A consumer then
/// has a schema that accepts any string where the format allows two values. This links the
/// two, which is what makes the schema check a value rather than only describe it.
///
/// Skipped for a field marked `x-audit-open`, whose values come from whichever emitter
/// produced the record, and for a field fed by more than one vocabulary — `action_name` is
/// both. Those stay plain strings, because no single definition lists what they can hold.
fn link_value_sets(defs: &mut BTreeMap<String, Value>, regs: &[&Registration]) {
    let mut by_field: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    for reg in regs {
        // Values only: a key vocabulary's names are keys of an object, not the values of a
        // property, so there is no property for them to point at.
        if let Kind::Values { field, .. } = reg.kind {
            by_field
                .entry(field)
                .or_default()
                .push(short_type_name((reg.type_name)()));
        }
    }
    let single: BTreeMap<&str, &String> = by_field
        .iter()
        .filter_map(|(field, owners)| match owners.as_slice() {
            [only] => Some((*field, only)),
            _ => None,
        })
        .collect();

    for schema in defs.values_mut() {
        let Some(properties) = schema.get_mut("properties").and_then(Value::as_object_mut) else {
            continue;
        };
        for (name, spec) in properties.iter_mut() {
            let Some(owner) = single.get(name.as_str()) else {
                continue;
            };
            let Some(object) = spec.as_object_mut() else {
                continue;
            };
            // Only a bare string. A property that already has a `$ref`, an `enum` or a
            // `const` says what it holds, and one marked open says it cannot be listed.
            let bare = object.get("type").and_then(Value::as_str) == Some("string")
                && !object.contains_key("enum")
                && !object.contains_key("const")
                && !object.contains_key("x-audit-open");
            if !bare {
                continue;
            }
            object.remove("type");
            object.insert("$ref".into(), json!(format!("#/$defs/{owner}")));
        }
    }
}

/// The crate schema of one crate: the definitions of the audit types it declares, for the
/// emitter it belongs to. Written by that crate's own unit tests, where its registrations are
/// certainly linked; committed as `audit-schema.json` at the crate root.
///
/// # Panics
///
/// If the crate registered nothing, or the registry is absent; see
/// [`Registration::require_registry`].
#[must_use]
pub fn crate_schema(defining_crate: &str) -> Value {
    Registration::require_registry();
    let regs = registrations(|r| r.defining_crate == defining_crate);
    let first = regs
        .first()
        .unwrap_or_else(|| panic!("crate `{defining_crate}` registered no audit types"));
    let emitter = first.emitter_name;
    let format = first.emitter_format;
    assert!(
        regs.iter().all(|r| r.emitter_name == emitter),
        "crate `{defining_crate}` registers types for more than one emitter"
    );
    let defs = definitions(&regs);
    json!({
        "$schema": SCHEMA_DIALECT,
        "title": format!("Audit types declared by crate {defining_crate}"),
        "x-audit-emitter": { "name": emitter, "format": format },
        "x-audit-crate": defining_crate,
        "$defs": Value::Object(defs.into_iter().collect::<Map<_, _>>()),
    })
}

/// Merge the committed crate schemas of one emitter into its schema.
///
/// # Panics
///
/// If the crate schemas name different emitters or formats, or two of them define the same
/// name differently.
#[must_use]
pub fn merge_crate_schemas(crate_schemas: &[Value]) -> Value {
    let first = crate_schemas.first().expect("at least one crate schema");
    let emitter = first["x-audit-emitter"].clone();
    let mut defs: BTreeMap<String, Value> = BTreeMap::new();
    for fragment in crate_schemas {
        assert_eq!(
            fragment["x-audit-emitter"], emitter,
            "crate schema {} names another emitter or format",
            fragment["x-audit-crate"]
        );
        for (name, def) in fragment["$defs"].as_object().expect("$defs") {
            if let Some(existing) = defs.get(name) {
                assert_eq!(
                    existing, def,
                    "`{name}` is defined differently by two crate schemas ({})",
                    fragment["x-audit-crate"]
                );
            }
            defs.insert(name.clone(), def.clone());
        }
    }
    let name = emitter["name"].as_str().unwrap_or("?");
    json!({
        "$schema": SCHEMA_DIALECT,
        "title": format!("Audit records emitted by {name}"),
        "x-audit-emitter": emitter,
        "$defs": Value::Object(defs.into_iter().collect::<Map<_, _>>()),
    })
}

/// The type's name without module path or generics: the key it gets under `$defs`.
#[must_use]
pub fn short_type_name(full: &str) -> String {
    let tail = full.rsplit("::").next().unwrap_or(full);
    tail.split('<').next().unwrap_or(tail).to_string()
}

/// The schema of everything the emitter `emitter` can put on the wire, from the registrations
/// linked into this binary. Complete only where every crate of the emitter is linked and
/// referenced; the committed schema is assembled from crate schemas instead, see the module
/// docs.
///
/// # Panics
///
/// If nothing is registered for the emitter, or the registry is absent.
#[must_use]
pub fn audit_schema_for(emitter: &str) -> Value {
    Registration::require_registry();
    let regs = registrations(|r| r.emitter_name == emitter);
    let first = regs
        .first()
        .unwrap_or_else(|| panic!("no audit types registered for emitter `{emitter}`"));
    let format = first.emitter_format;
    let defs = definitions(&regs);
    json!({
        "$schema": SCHEMA_DIALECT,
        "title": format!("Audit records emitted by {emitter}"),
        "x-audit-emitter": { "name": emitter, "format": format },
        "$defs": Value::Object(defs.into_iter().collect::<Map<_, _>>()),
    })
}

/// The schema as a pretty-printed document with a trailing newline, as committed.
///
/// # Panics
///
/// If the value does not serialize, which a schema built by this module always does.
#[must_use]
pub fn render(schema: &Value) -> String {
    let mut text = serde_json::to_string_pretty(schema).expect("a schema serializes");
    text.push('\n');
    text
}

/// The crate schema file of a crate: `audit-schema.json` at its root.
#[must_use]
pub fn crate_schema_path(manifest_dir: &str) -> std::path::PathBuf {
    std::path::Path::new(manifest_dir).join("audit-schema.json")
}

/// The environment variable that switches the crate schema and schema tests from comparing to
/// writing.
pub const UPDATE_ENV: &str = "LAKEKEEPER_UPDATE_AUDIT_SCHEMA";

/// Assert that the committed crate schema of `defining_crate` equals what its registry
/// generates, or write it when [`UPDATE_ENV`] is set. For use in that crate's own tests, so the
/// registrations are certainly linked.
///
/// # Panics
///
/// If the committed crate schema is missing or stale. That is the point: this is for use in
/// tests.
pub fn assert_crate_schema_committed(defining_crate: &str, manifest_dir: &str) {
    let path = crate_schema_path(manifest_dir);
    let generated = render(&crate_schema(defining_crate));
    if std::env::var_os(UPDATE_ENV).is_some() {
        std::fs::write(&path, &generated)
            .unwrap_or_else(|e| panic!("writing {}: {e}", path.display()));
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cannot read the committed crate schema {}: {e}\n\nGenerate it with `just update-audit-schema`.",
            path.display()
        )
    });
    assert!(
        committed == generated,
        "the committed crate schema {} is not what the registry generates. Run `just update-audit-schema` and review the diff: it is what a consumer of the audit log will see.",
        path.display()
    );
}

/// Assert that no two vocabularies keying the same object declare the same key.
///
/// The `context` map of an authorization record is one flat object, and `keys_of =
/// "context"` is the one vocabulary form open to an emitter outside this repository. So two
/// products can reach the same key of the same object. One key, one meaning: a second
/// declaration is a second meaning at one path in one record, and whichever handler writes
/// last decides which of them a consumer sees.
///
/// Reads the whole registry rather than one crate's, so it sees every vocabulary linked into
/// the binary that runs it. Run from an emitting crate's own tests it therefore compares that
/// crate's keys against Lakekeeper's, which is the pairing that can clash.
///
/// A name reused at a *different* path is not this. `actor.principal` and `context.principal`
/// are two fields named for where they sit, which is why the reference tells a consumer to
/// address fields by path.
///
/// # Panics
///
/// If one object has the same key from two vocabularies.
pub fn assert_no_object_declares_a_key_twice() {
    Registration::require_registry();
    let mut owners: BTreeMap<(&str, &str), Vec<String>> = BTreeMap::new();
    for reg in registrations(|_| true) {
        let Kind::Keys { object, .. } = reg.kind else {
            continue;
        };
        let owner = short_type_name((reg.type_name)());
        for key in reg.kind.names().iter().map(|name| name.text) {
            owners.entry((object, key)).or_default().push(owner.clone());
        }
    }
    let clashes: Vec<String> = owners
        .iter()
        .filter(|(_, declared_by)| declared_by.len() > 1)
        .map(|((object, key), declared_by)| {
            format!(
                "{object}: `{key}` is declared by {}",
                declared_by.join(" and ")
            )
        })
        .collect();
    assert!(
        clashes.is_empty(),
        "these keys are declared twice for one object:\n  {}\n\n\
         A key names one thing. Two vocabularies declaring it for the same object put two \
         meanings at one path in one record, and the handler that writes last decides which \
         one a consumer sees. Rename one of them, or have the second use the first rather \
         than declaring its own.",
        clashes.join("\n  ")
    );
}

/// Every Rust source under `dir`, read into `out`.
fn rust_sources(dir: &std::path::Path, out: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "target") {
                continue;
            }
            rust_sources(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs")
            && let Ok(text) = std::fs::read_to_string(&path)
        {
            out.push(text);
        }
    }
}

/// A name with its separators and case removed, so two spellings of one name compare equal.
///
/// The source names a variant, `DryRun`; the registry names what that variant puts on the
/// wire, `dry_run`. Both reduce to `dryrun`. A variant the attribute renames to something
/// else entirely still differs, which is the case worth a human reading it.
fn normalized(name: &str) -> String {
    name.chars()
        .filter(char::is_ascii_alphanumeric)
        .map(|c| c.to_ascii_lowercase())
        .collect()
}

/// What a scan of one source found: the body of every `fn event_actions` defined in it, and
/// how many anchors were a trait declaration rather than a definition.
///
/// The counts are returned so the caller can account for every anchor. A body is found by
/// matching braces, and an unbalanced one — a `{` inside a string literal, say — would end a
/// body early or run off the end, dropping keys without failing anything.
struct EventActions<'a> {
    bodies: Vec<&'a str>,
    declarations: usize,
}

/// The body of every `fn event_actions` defined in `text`, braces balanced.
///
/// Anchored on the open paren, so neither a longer name beginning the same way nor a mention
/// of the function in prose is taken for a definition.
fn event_actions_bodies(text: &str) -> EventActions<'_> {
    let mut found = EventActions {
        bodies: Vec::new(),
        declarations: 0,
    };
    for (at, _) in text.match_indices("fn event_actions(") {
        let rest = &text[at..];
        let open = rest.find('{');
        // A trait declaration ends at the semicolon and has no body of its own.
        if rest
            .find(';')
            .is_some_and(|end| open.is_none_or(|o| end < o))
        {
            found.declarations += 1;
            continue;
        }
        let Some(open) = open.map(|o| at + o) else {
            found.declarations += 1;
            continue;
        };
        let mut depth = 0usize;
        for (offset, ch) in text[open..].char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        found.bodies.push(&text[open..=open + offset]);
                        break;
                    }
                }
                _ => {}
            }
        }
    }
    found
}

/// The action a chain names, as a registry key, from `action_name(Vocabulary::Variant`.
///
/// Normalised rather than converted to the wire spelling, so the variant's own case and the
/// enum's rename rule do not have to be reproduced here.
fn action_named_in(body: &str) -> Option<String> {
    let at = body.find("action_name(")? + "action_name(".len();
    let window: String = body[at..].chars().take(120).collect();
    identifier_after(&window, "::").map(|variant| normalized(&variant))
}

/// Every `context` key an `event_actions` body writes is one its action declares.
///
/// An action's keys are usually the fields of the variant naming it, which the attribute
/// reads directly. A handler that names an action and then assembles the context itself
/// writes them in an `event_actions` body, where no attribute can see them — it declares
/// them with `#[audit(carries = "...")]`, and this is what holds that list to the code.
///
/// Scoped to `event_actions` because that is the shape this covers: one chain, one action
/// named by a literal, its keys written beside it. The other place keys are written,
/// `action_descriptor`, spreads them across the arms of one match under a single builder,
/// where no text scan can tell which arm a key belongs to — those keys are the variant's
/// fields, so the attribute already has them.
///
/// Unlike the fixture guard this needs no fixture, so it covers an action nobody pinned.
///
/// # Panics
///
/// If a body writes a key its action does not declare, or if the scan finds no body naming a
/// known action, which means it is reading the wrong tree.
pub fn assert_event_actions_write_only_declared_keys<E: super::AuditEmitter>(
    crates_dir: &std::path::Path,
) {
    Registration::require_registry();

    // Keyed by the normalised name so a `Vocabulary::Variant` in the source matches without
    // reproducing the enum's rename rule here; the wire spelling rides along for the message.
    let mut declared: BTreeMap<String, (&str, BTreeSet<&str>)> = BTreeMap::new();
    // Across every emitter: an action name belongs to whoever declared it, and a product's
    // own action carries Lakekeeper's keys, so neither side of the pairing is this emitter's
    // alone.
    for reg in registrations(|_| true) {
        if let Kind::Values {
            field: "action_name",
            names,
        } = reg.kind
        {
            for name in names {
                declared
                    .entry(normalized(name.text))
                    .or_insert_with(|| (name.text, BTreeSet::new()))
                    .1
                    .extend(name.carries.iter().copied());
            }
        }
    }

    let mut sources = Vec::new();
    rust_sources(crates_dir, &mut sources);

    let mut checked = 0usize;
    let mut named = 0usize;
    let mut accounted = 0usize;
    let mut anchors = 0usize;
    let mut undeclared = Vec::new();
    for text in &sources {
        anchors += text.matches("fn event_actions(").count();
        let found = event_actions_bodies(text);
        accounted += found.bodies.len() + found.declarations;
        for body in found.bodies {
            // A body naming no action in a vocabulary names one of another emitter, or a
            // literal a test stands up. Either way there is nothing here to hold it to.
            let Some(action) = action_named_in(body) else {
                continue;
            };
            named += 1;
            let Some((wire, keys)) = declared.get(&action) else {
                continue;
            };
            checked += 1;
            for (at, _) in body.match_indices("ContextKey::") {
                let window: String = body[at..].chars().take(80).collect();
                let Some(variant) = identifier_after(&window, "ContextKey::") else {
                    continue;
                };
                let written = normalized(&variant);
                if !keys.iter().any(|key| normalized(key) == written) {
                    undeclared.push(format!("`{wire}` writes undeclared `{variant}`"));
                }
            }
        }
    }

    // A body is found by matching braces, so an unbalanced one — a `{` inside a string
    // literal, say — would end a body early and skip the keys after it without failing.
    // Counting the bodies against the declarations is what makes that a failure.
    assert_eq!(
        accounted, anchors,
        "accounted for {accounted} of {anchors} `event_actions` in the sources, so brace \
         matching lost one and its keys went unchecked"
    );
    assert!(
        !sources.is_empty(),
        "no Rust source under {}, so this is scanning the wrong tree",
        crates_dir.display()
    );
    // A body that names no action is a delegating impl — it hands the work to the actions it
    // holds — and a crate may have only those, or none at all, when its actions reach the
    // wire through another product's event context. What would be wrong is bodies that do
    // name actions, none of which any emitter registers.
    assert!(
        named == 0 || checked > 0,
        "{named} `event_actions` name an action and not one is registered, so this is \
         reading names nothing declares"
    );
    undeclared.sort_unstable();
    undeclared.dedup();
    assert!(
        undeclared.is_empty(),
        "these `event_actions` bodies write a key the action does not declare:\n  {}\n\n\
         The schema tells a consumer which keys an action carries, so one written without \
         being declared is invisible to them. Add it to the variant's \
         `#[audit(carries = \"...\")]`.",
        undeclared.join("\n  ")
    );
}

/// The identifier following the first `prefix` in `block`, or `None` when there is none.
fn identifier_after(block: &str, prefix: &str) -> Option<String> {
    let at = block.find(prefix)? + prefix.len();
    let identifier: String = block[at..]
        .chars()
        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect();
    (!identifier.is_empty()).then_some(identifier)
}

/// Every closed set a key draws its value from is a vocabulary that emitter registers.
///
/// `values_of` is a reference, written as a schema name, and the branch that names the key
/// publishes it as a `$ref`. A name nothing provides resolves to nothing, and a name that
/// belongs to a part rather than a vocabulary would tell a consumer to expect an object
/// where a string arrives.
///
/// # Panics
///
/// If a key names a set no value vocabulary of that emitter provides.
pub fn assert_declared_value_sets_are_vocabularies<E: super::AuditEmitter>() {
    Registration::require_registry();
    let known: BTreeSet<String> = registrations(|reg| reg.emitter_name == E::NAME)
        .iter()
        .filter(|reg| matches!(reg.kind, Kind::Values { .. }))
        .map(|reg| short_type_name((reg.type_name)()))
        .collect();

    let mut dangling = Vec::new();
    for reg in registrations(|reg| reg.emitter_name == E::NAME) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        let owner = short_type_name((reg.type_name)());
        for name in names {
            if let Some(vocabulary) = name.values
                && !known.contains(vocabulary)
            {
                dangling.push(format!(
                    "{owner}: key `{}` of `{object}` draws its value from `{vocabulary}`, \
                     which is no vocabulary of this emitter",
                    name.text
                ));
            }
        }
    }
    assert!(
        dangling.is_empty(),
        "these keys name a value set their emitter does not declare:\n  {}\n\n\
         `values_of` points at a value vocabulary — an enum carrying \
         `#[audit_part(field = \"...\")]` — by its schema name. Check the spelling, and that \
         the type is a vocabulary rather than a part.",
        dangling.join("\n  ")
    );
}

/// Every shape a key declares is a type that emitter registers.
///
/// `#[audit(holds = "...")]` names its shape as a string, so a typo compiles and publishes a
/// `$ref` into a customer-facing schema that resolves to nothing. Nothing else looks: the
/// generator copies the name through, and the format checker only diffs it against the last
/// one. This is what makes the name a reference rather than a spelling.
///
/// # Panics
///
/// If a key names a shape no registration of that emitter provides.
pub fn assert_declared_shapes_are_registered<E: super::AuditEmitter>() {
    Registration::require_registry();
    let known: BTreeSet<String> = registrations(|reg| reg.emitter_name == E::NAME)
        .iter()
        .filter(|reg| matches!(reg.kind, Kind::Part | Kind::Context | Kind::Shape { .. }))
        .filter_map(|reg| reg.schema_name.map(|name| name().to_string()))
        .collect();

    let mut dangling = Vec::new();
    for reg in registrations(|reg| reg.emitter_name == E::NAME) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        let owner = short_type_name((reg.type_name)());
        for name in names {
            if let Some(shape) = name.shape
                && !known.contains(shape)
            {
                dangling.push(format!(
                    "{owner}: key `{}` of `{object}` holds `{shape}`, which is not registered",
                    name.text
                ));
            }
        }
    }
    assert!(
        dangling.is_empty(),
        "these keys name a shape their emitter does not declare:\n  {}\n\n\
         `holds` is a reference to a registered type, written as its schema name. The schema \
         points a consumer at it by `$ref`, so a name nothing provides publishes a reference \
         that resolves to nothing. Check the spelling, and that the type carries \
         `#[audit_part]` and belongs to this emitter.",
        dangling.join("\n  ")
    );
}

/// Every `context` key an emitter declares is pushed by some call under `crates_dir`.
///
/// A key vocabulary is pinned by the schema: rename or drop a name and the format moves, and
/// the checker reports it. A `push_extra_context` call deleted in a refactor is invisible
/// there. The key leaves the wire, the enum that declares it stays, the schema diff is empty,
/// and a field a consumer reads is gone with nothing to announce it. This reads the registry
/// for the keys and the source for the pushes.
///
/// The source is read rather than a record captured because these keys ride on a record their
/// own crate does not assemble: an emitter outside Lakekeeper pushes keys onto an
/// authorization record that Lakekeeper stamps, so that crate has no record of its own to
/// capture them from.
///
/// One push site is enough to pass. A key pushed from two places passes while either remains.
///
/// # Panics
///
/// If a declared key has no push site, or if the scan finds no sources or no push sites,
/// which means it is pointed at the wrong tree.
pub fn assert_every_context_key_is_pushed<E: super::AuditEmitter>(crates_dir: &std::path::Path) {
    Registration::require_registry();

    let mut declared: BTreeMap<String, Vec<&'static str>> = BTreeMap::new();
    for reg in registrations(|reg| reg.emitter_name == E::NAME) {
        let Kind::Keys { object, names } = reg.kind else {
            continue;
        };
        if object != "context" {
            continue;
        }
        declared
            .entry(short_type_name((reg.type_name)()))
            .or_default()
            .extend(names.iter().map(|name| name.text));
    }
    assert!(
        !declared.is_empty(),
        "emitter `{}` has no `context` key vocabulary in this registry, so either it declares          none or the crate that declares one is not linked into this test binary.",
        E::NAME
    );

    let mut sources = Vec::new();
    rust_sources(crates_dir, &mut sources);
    assert!(
        sources.len() > 10,
        "only {} Rust sources under {}, so this is scanning the wrong tree",
        sources.len(),
        crates_dir.display()
    );

    let mut pushed: BTreeSet<(String, String)> = BTreeSet::new();
    for text in &sources {
        for (at, _) in text.match_indices("push_extra_context") {
            // The call, bounded generously: the key is its first argument, and the longest of
            // these calls wraps over a few lines. Bounded in CHARACTERS: a byte slice that
            // lands inside a multi-byte character panics, and these sources are full of em
            // dashes.
            let block: String = text[at..].chars().take(400).collect();
            for vocabulary in declared.keys() {
                if let Some(variant) = identifier_after(&block, &format!("{vocabulary}::")) {
                    pushed.insert((vocabulary.clone(), normalized(&variant)));
                }
            }
        }
    }
    assert!(
        !pushed.is_empty(),
        "no `push_extra_context` call under {} names a declared key, so this is scanning the \
         wrong tree",
        crates_dir.display()
    );

    let mut missing: Vec<String> = Vec::new();
    for (vocabulary, keys) in &declared {
        for key in keys {
            if !pushed.contains(&(vocabulary.clone(), normalized(key))) {
                missing.push(format!("{vocabulary}::{key}"));
            }
        }
    }
    assert!(
        missing.is_empty(),
        "these `context` keys are declared and pushed nowhere:\n  {}\n\n\
         A key nothing pushes is a field the schema promises and no record carries. Push it, \
         or drop it from the vocabulary and write the fragment its removal owes.",
        missing.join("\n  ")
    );
}

/// Whether `name` is one or more runs of `[a-z0-9]` joined by single underscores, starting
/// with a letter.
///
/// Checking the characters alone would accept a leading, trailing or doubled underscore.
fn is_lower_snake_case(name: &str) -> bool {
    name.starts_with(|c: char| c.is_ascii_lowercase())
        && name.split('_').all(|segment| {
            !segment.is_empty()
                && segment
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        })
}

/// Assert that the wire names `defining_crate` declares are house style: usable by a consumer
/// at all, and `lower_snake_case` unless the declaring type is marked `external_values`.
///
/// Every key is held to the rule, and so is every value, because a record spells its names
/// the way the rest of the log does. A value vocabulary spelled somewhere else is marked and
/// skipped. The default is to check, so a vocabulary cannot go unchecked by being left off a
/// list.
///
/// Renaming a name shows up as a schema difference and the format check calls it a breaking
/// change. Adding one does not, because an addition breaks no consumer, so a new name spelled
/// the wrong way would reach a release unremarked. This is the check for that.
///
/// # Panics
///
/// If a name is empty, carries whitespace, or is not `lower_snake_case` without being marked.
pub fn assert_wire_values_are_house_style(defining_crate: &str) {
    Registration::require_registry();
    let mut malformed = Vec::new();
    for reg in registrations(|r| r.defining_crate == defining_crate) {
        let Some(field) = reg.kind.wire_place() else {
            continue;
        };
        if reg.external_values {
            continue;
        }
        let owner = short_type_name((reg.type_name)());
        let what = if matches!(reg.kind, Kind::Keys { .. }) {
            "key"
        } else {
            "value"
        };
        for value in reg.kind.names().iter().map(|name| name.text) {
            if value.is_empty() || value.chars().any(char::is_whitespace) {
                malformed.push(format!("{field}: {owner} -> {value:?} is unusable"));
            } else if !is_lower_snake_case(value) {
                malformed.push(format!(
                    "{field}: {owner} -> {what} `{value}` is not lower_snake_case"
                ));
            }
        }
    }
    assert!(
        malformed.is_empty(),
        "these wire names are not house style:\n  {}\n\n\
         A name is one or more runs of `[a-z0-9]` joined by single underscores, starting with \
         a letter, which is how every line in this log spells a name. An enum that lost its \
         case style, gained a different one, or carries a hand-written rename that does not \
         follow it lands here. Fix the spelling now: once released, changing it renames \
         something consumers match on. If these values are spelled somewhere else — another \
         product publishes them, or they mirror a vocabulary that does — add `external_values` \
         to the enum's `#[audit_part(...)]` and name that vocabulary in its doc comment.",
        malformed.join("\n  ")
    );
}
