[working-directory: "../.."]
build-local-image:
    docker build -t localhost/lakekeeper-local:amd64 -f docker/full.Dockerfile .

# When running on your machine, make sure to build the image of local lakekeeper with
# `build-local-image`.
test_migration:
    # Initialize lakekeeper (previous release), create + drop tables.
    docker compose run spark /opt/entrypoint.sh \
        bash -c "cd /opt/tests/migrations && source setup.sh && python3 spark.py write_data"
    # Start lakekeeper with locally built binary. Triggers migration with that binary.
    # Flag --wait ensures the service is up and healthy before the next command executes.
    docker compose up --detach --wait lakekeeper_2
    # Verify we can still read data from the pod started before the migration.
    docker compose run spark /opt/entrypoint.sh \
        bash -c "cd /opt/tests/migrations && source setup.sh && python3 spark.py read_data"
    docker compose down -v
