[working-directory: "../.."]
build-local-lk:
    docker build -t localhost/lakekeeper-local:latest -f docker/full.Dockerfile .

test_migration:
    docker compose run --rm spark /opt/entrypoint.sh \
        bash -c "cd /opt/tests/migrations && source setup.sh && python3 spark.py"
    docker compose down -v lakekeeper_initial
    # Start lakekeeper with locally built binary. Triggers migration with that binary.
    # Flag --wait ensures the service is up and healthy before the next command executes.
    docker compose up --detach --wait lakekeeper_2
    docker compose down -v

# test_migration:
#     # Initialize lakekeeper, create + drop tables
#     env LAKEKEEPER_IMAGE="quay.io/lakekeeper/catalog:latest-main" docker compose run --rm spark /opt/entrypoint.sh \
#         bash -c "cd /opt/tests/migrations && source setup.sh && python3 spark.py"
#     # Make sure lakekeeper is stopped
#     env LAKEKEEPER_IMAGE="quay.io/lakekeeper/catalog:latest-main" docker compose down
#     # Start new lakekeeper build and run its migration
#     env LAKEKEEPER_IMAGE="localhost/lakekeeper-local:latest" docker compose up lakekeeper
