name: Docs Link Check

on:
  push:
    branches:
      - main
      - "manual-release-*"
      - "rel-*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # Needed to checkout code

jobs:
  linkcheck:
    name: Link Check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.x
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4
        with:
          just-version: 1.x
      - uses: taiki-e/install-action@91ddec75689c4c78665b598d188dc821c5a43e5c # v2
        with:
          tool: lychee
      - name: Link check (nightly anchors + assembled-site files)
        run: just linkcheck
        working-directory: ./site
