name: integration tests

on:
  push:
    branches:
      - main
      - 'manual-release-*'
  pull_request:
    branches:
      - main
      - 'manual-release-*'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker_build.yml
    with:
      platform: 'amd64'
      dockerfile: 'docker/full.Dockerfile'
      image_name: 'iceberg-catalog-local'
  tests:
    needs: docker
    strategy:
      fail-fast: false
      matrix:
        names: [ pyiceberg, spark_openfga, spark_adls, spark_aws_remote_signing, spark_aws_sts, spark_gcs, spark_minio_sts, spark_minio_remote_signing, starrocks, trino ]
    uses: ./.github/workflows/integration_test_workflow.yml
    with:
        test_name: ${{ matrix.names }}
    secrets: inherit