name: IntegrationTestSpawner

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
      test_matrix:
        strategy:
          fail-fast: false
          matrix:
            names: [ openfga, pyiceberg, spark_adls, spark_aws, spark_gcs, spark_minio, starrocks, trino ]
        uses: ./.github/workflows/integration_tests.yml
        with:
            test_name: ${{ matrix.names }}
        secrets: inherit