name: Kubernetes auth integration test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker_build.yml
    with:
      platform: 'amd64'
      dockerfile: 'docker/full.Dockerfile'
      image_name: 'iceberg-catalog-local'
  kube_auth:
    needs: docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: engineerd/setup-kind@v0.6.2
        with:
          version: "v0.24.0"
      - name: Restore binary
        uses: actions/download-artifact@v4
        with:
          name: iceberg-catalog-image
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -Rlh artifacts

      - name: Restore Docker image
        run:  docker load -i artifacts/iceberg-catalog-local-amd64.tar &&  kind load docker-image localhost/iceberg-catalog-local:amd64
      - uses: azure/setup-helm@v4.2.0
        id: install
      - run: helm repo add lakekeeper https://lakekeeper.github.io/lakekeeper-charts/
        name: Add lakekeeper helm repo
      - name: Install lakekeeper (wait 300s)
        run: helm install -f tests/kube-auth/values.yaml my-lakekeeper lakekeeper/lakekeeper --version 0.3.0 && sleep 300
      - name: Run tests
        run: kubectl run bootstrap-test --image=curlimages/curl -it --command=true --restart=Never -- /bin/sh -c "$(cat tests/kube-auth/bootstrap.sh)"
      - name: bootstrap-logs
        if: failure()
        run: kubectl logs bootstrap-test
      - name: server-logs
        if: failure()
        run : kubectl logs deployments/my-lakekeeper